### ISSUE TITLE
Got an error while building the app using lib

### ISSUE THREAD

**Issue by nqhhdev** [WalletConnect/WalletConnectFlutterV2#1]
Step 1 : 
- I fork your project to my GitHub
Step 2:
- I install WalletConnectDartV2 to my project and try run it.
- I got the error msg in the console 

<img width="1241" alt="Screenshot 2023-02-15 at 01 08 37" src="https://user-images.githubusercontent.com/99852347/218821348-1f3ad2f5-6d96-475f-bb43-f2714fb93471.png">

Pls help me check it and feedback to me

My project use :

- Flutter version 3.7.0 on channel stable
- Dart version 2.19.0

**Comment by Luzzotica** [comment]
It looks like you are using GraphQLWebsocketChannel here, which seems odd. Is that part of your project already?

This repo uses the `web_socket_channel: ^2.2.0` package.

My flutter version is less than yours though. Perhaps you have a more up to date version of web socket channel that removes the `ready` property. I'll take a look.

**Comment by Luzzotica** [comment]
Please try using the most recent official release:

https://pub.dev/packages/walletconnect_flutter_v2

**Comment by nqhhdev** [comment]
Got It, thank u 🚀

**Comment by Luzzotica** [comment]
@nqhhdev Let me know if it works alright.
If it does I'll close this out.

If it doesn't, I'll need the list of dependencies you have in your pubspec.

**Comment by mik3mast3rs** [comment]
I also have this issue. And here is why:

https://pub.dev/packages/web_socket_channel/changelog

That `ready` property was added to WebSocketChannel in the version `2.3.0`, but the minimum version of the library `web_socket_channel` is set to 2.2.0 in the WalletConnect library. It should be upgraded to 2.3.0.

As a temporary fix, you can modify the version of web_socket_channel to 2.3.0 in the pubspec.lock

**Comment by Luzzotica** [comment]
Just publish v1.0.2 that resolves this, thank you!
