### ISSUE TITLE
How to store a session for next time use

### ISSUE THREAD

**Issue by mmMrz** [WalletConnect/WalletConnectFlutterV2#107]
I see an option for storage in initialization

But I don't know how to store the session for next use, and I haven't seen any relevant instructions or examples in the document

Hope to explain

**Comment by Luzzotica** [comment]
The sessions are automatically stored when you create a new one as long as you don't set `memoryStore = true` when you instantiate the client.

All you have to do is query the client for current sessions using `signClient.getActiveSessions()`

**Comment by mmMrz** [comment]
@Luzzotica Thank you very much for your kind attention personal response! I still have a question about this, it's if I use the disconnectSession of Web3Wallet, did it will delete the session from storage? or how can I disconnectSession and delete sessions?
Annnnd, Thank you. again. Your previous development in the Dart version of WalletConnect V1 has been very helpful to me!

**Comment by Luzzotica** [comment]
I didn't work on the WalletConnect V1 library, but thank you for your comments!

If you call the `disconnectSession` the session will be deleted, yes.

So only call that when the user "logs out" or wants to connect with a different device.
