### ISSUE TITLE
How to connect with MetaMask ?

### ISSUE THREAD

**Issue by nqhhdev** [WalletConnect/WalletConnectFlutterV2#113]
Hi team, I have a question about the support connected with `MetaMask`.
I saw  https://walletconnect.com/explorer and I don't see `MetaMask` support for V2.

- https://pub.dev/packages/walletconnect_dart Still support after 28 Jun?
- When does `WalletConnect V2` support `MetaMask`?

Thanks all for support

**Comment by Luzzotica** [comment]
MetaMask 7.0.1 on iOS supports WalletConnect v2 and I have tested it.
I am not sure what version of android supports v2, but it has also been released.

walletconnect_dart won't be supported once v1 is sunset as far as I'm aware. 
WalletConnect the organization didn't develop that library, but I believe the relays that support v1 will be turned off.

Any other questions?

**Comment by leeway1208** [comment]
How to get the uri that pairs with metamask?

**Comment by ContrastPro** [comment]
When I generate a link and try to open it with the launchUrlString or just launchUrl method, the metamask opens, but the modal window for the connection does not appear. But if you generate a qr code from this link and scan it with a regular smartphone camera, Metamask will open and a modal window for connection will appear. What could be the problem?
<img width="506" alt="Снимок экрана 2023-06-29 в 19 16 04" src="https://github.com/WalletConnect/WalletConnectFlutterV2/assets/49535226/be9b6300-39b6-4c95-bd8f-0dd4898740b3">

**Comment by bobwith2bees** [comment]
The URI provided by the FlutterV2 package does not appear to be encoded properly for direct use when converted to a string (to combine with your native link'.   

You can see this in the Web3Modal repository here:
https://github.com/WalletConnect/Web3ModalFlutter/blob/master/lib/utils/core_util.dart#L23

```dart
    String encodedWcUrl = Uri.encodeComponent(wcUri);
    LoggerUtil.logger.i('Encoded WC URL: $encodedWcUrl');

    return Uri.parse('${safeAppUrl}wc?uri=$encodedWcUrl');
```

**Comment by anthonnyGiong** [comment]
![Screenshot 2023-06-30 at 10 48 15](https://github.com@Luzzotica WalletConnect/WalletConnectFlutterV2/assets/113158928/ad17e058-1e9d-4ce2-ba3d-5e286f7aeb4a)

@Luzzotica I can't open MM when I call `connect()` func. Helpp me pls

**Comment by nqhhdev** [comment]
@Luzzotica I can't receive a response when I call connect() func. Helpp me pls
<img width="769" alt="Screenshot 2023-06-30 at 10 50 13" src="https://github.com/WalletConnect/WalletConnectFlutterV2/assets/99852347/e95193f3-1ed4-41b3-b4e4-0e8d0f10bc46">

**Comment by ContrastPro** [comment]
@nqhhdev check this [instruction](https://docs.walletconnect.com/2.0/cloud/relay) visit [site](https://cloud.walletconnect.com/) sign up and generate projectId.  Then your code could be like this to generate ConnectResponse. In this example, I connect to Polygon Mumbai Test net.


    final Web3App web3app = await Web3App.createInstance(
      projectId: 'c4f79cc821944d9680842e34466bfb',
      metadata: const PairingMetadata(
        name: 'Flutter WalletConnect',
        description: 'Flutter WalletConnect Dapp Example',
        url: 'https://walletconnect.com/',
        icons: [
          'https://walletconnect.com/walletconnect-logo.png',
        ],
      ),
    );

    final ConnectResponse response = await web3app.connect(
      requiredNamespaces: {
        'eip155': const RequiredNamespace(
          chains: [
            'eip155:80001',
          ],
          methods: [
            'personal_sign',
            'eth_sign',
            'eth_signTransaction',
            'eth_signTypedData',
            'eth_sendTransaction',
          ],
          events: [
            'chainChanged',
            'accountsChanged',
          ],
        ),
      },
    );

    final Uri? uri = response.uri;

**Comment by nqhhdev** [comment]
@ContrastPro 
No actions when I call `connect()` func....
```
 Future<ConnectResponse?> connect() async {
    if (_signClient != null) {
      final ConnectResponse response = await _signClient!.connect(
        requiredNamespaces: {
          'eip155': const RequiredNamespace(
            chains: [
              'eip155:1',
            ],
            methods: [
              'personal_sign',
              'eth_sign',
              'eth_signTransaction',
              'eth_signTypedData',
              'eth_sendTransaction',
            ],
            events: [
              'chainChanged',
              'accountsChanged',
            ],
          ),
        },
      );

    } else {
      return null;
    }
  }

  Future<void> initialize() async {
    try {
      _signClient = await SignClient.createInstance(
      projectId: '35621d94c14f8bed062cd2b617ab0328',
      metadata: const PairingMetadata(
        name: 'MoonFit',
        description: 'MoonFit is a Web3 & Lifestyle App that promotes active living by rewarding users anytime they burn calories through physical activities.',
        url: 'https://moonfit.xyz',
        icons: ['https://moonfit.xyz/assets/images/favicon/favicon-32x32.png'],
      ),
    );


    // Register event handlers

    // // Loop through all the chain data
    // for (final ChainMetadata chain in ChainData.allChains) {
    //   // Loop through the events for that chain
    //   for (final event in getChainEvents(chain.type)) {
    //     _web3App!.registerEventHandler(chainId: chain.chainId, event: event);
    //   }
    // }
    //
      _signClient!.onSessionPing.subscribe((ping) {
      log('onSessionPing $ping');
    });
      _signClient!.onSessionEvent.subscribe((event) {
      log('onSessionEvent $event');
    });


    } on WalletConnectError catch (e) {
      log(e.message);
    }
  }
```

**Comment by ContrastPro** [comment]
@nqhhdev update Metamask to last available version on Google/App store. Then try my code with your projectId. Don't forget to close your app every time when you try to connect.

![Снимок экрана 2023-06-30 в 09 38 13](https://github.com/WalletConnect/WalletConnectFlutterV2/assets/49535226/f3aa5861-f054-4a10-b0d0-271f19a1cec6)


```
  Future<void> createSession() async {
    final Web3App web3app = await Web3App.createInstance(
      projectId: 'c4f79cc821944d9680842e34466bfb',
      metadata: const PairingMetadata(
        name: 'Flutter WalletConnect',
        description: 'Flutter WalletConnect Dapp Example',
        url: 'https://walletconnect.com/',
        icons: [
          'https://walletconnect.com/walletconnect-logo.png',
        ],
      ),
    );

    final ConnectResponse response = await web3app.connect(
      requiredNamespaces: {
        'eip155': const RequiredNamespace(
          chains: [
            'eip155:1',
          ],
          methods: [
            'personal_sign',
            'eth_sign',
            'eth_signTransaction',
            'eth_signTypedData',
            'eth_sendTransaction',
          ],
          events: [
            'chainChanged',
            'accountsChanged',
          ],
        ),
      },
    );

    final Uri? uri = response.uri;

    if (uri != null) {
      final String encodedUri = Uri.encodeComponent('$uri');

      await launchUrlString(
        'metamask://wc?uri=$encodedUri',
        mode: LaunchMode.externalApplication,
      );
    }
  }
```

**Comment by nqhhdev** [comment]
@ContrastPro In Just moments I tried it, it work fine

**Comment by nqhhdev** [comment]
Now we need to try send some request `wallet_switchEthereumChain`, `wallet_addEthereumChain`, `eth_sendTransaction`

**Comment by nqhhdev** [comment]
@ContrastPro How to manage session?

**Comment by ContrastPro** [comment]
@nqhhdev I work with Polygon/Mumbai network and don't use some methods. I will be work with auth, send, sign transactions and may be with some other methods. At the moment, I have not implemented anything other than connecting to the Metamask methods.

**Comment by nqhhdev** [comment]
Lett me try it, and discus herreee !!! GOGOGO

**Comment by AnhTu6610** [comment]
> Now we need to try send some request `wallet_switchEthereumChain`, `wallet_addEthereumChain`, `eth_sendTransaction`
I write a function to switchChain BSC testnet, but it only runs to authClient!.request and doesn't have any action on metamask:
  Future switchChain(SessionConnect sessionConnect) async {
    logI(sessionConnect.session.pairingTopic, tag: "pairingTopic");
    launchUrlString("wc:${sessionConnect.session.topic}");
    var req = await authClient!.request(
      topic: sessionConnect.session.topic,
      chainId: "eip155:97",
      request: SessionRequestParams(
        method: "wallet_switchEthereumChain",
        params: [
          {"chainId": chainIdHex},
        ],
      ),
    );
    logI(req, tag: ">>>>>>>>>>>>>>>  req");
  }

**Comment by wufd** [comment]
[metamask issues] (https://github.com/MetaMask/metamask-mobile/issues/6655)

**Comment by Jens05** [comment]
Nothing is working at the moment. I try to connect to metamask and to trustwallet with their example app, but it just doesnt show a connection request... Any help / updates?

**Comment by nqhhdev** [comment]
> Nothing is working at the moment. I try to connect to metamask and to trustwallet with their example app, but it just doesnt show a connection request... Any help / updates? 

Pls you can try example of @ContrastPro

**Comment by Jens05** [comment]
> > Nothing is working at the moment. I try to connect to metamask and to trustwallet with their example app, but it just doesnt show a connection request... Any help / updates?
> 
> Pls you can try example of @ContrastPro

tried that too, didnt work for me sadly

**Comment by Jens05** [comment]
> > Nothing is working at the moment. I try to connect to metamask and to trustwallet with their example app, but it just doesnt show a connection request... Any help / updates?
> 
> Pls you can try example of @ContrastPro

trying to connect to bnb chain btw

**Comment by Luzzotica** [comment]
@Jens05 What is the precise namespace that you are using to connect to BNB?

I can't even find the chain ID for it.

**Comment by Jens05** [comment]
> @Jens05 What is the precise namespace that you are using to connect to BNB?
> 
> I can't even find the chain ID for it.

i use 'eip155:56', But in another issue i describe a problem i have, because metamask is opening, but no request is shown. This is also the case for Trustwallet, so its a plugin-related issue

**Comment by AnhTu6610** [comment]
> > Now we need to try send some request `wallet_switchEthereumChain`, `wallet_addEthereumChain`, `eth_sendTransaction`
> > I write a function to switchChain BSC testnet, but it only runs to authClient!.request and doesn't have any action on metamask:
> 
> ```
>   Future switchChain(SessionConnect sessionConnect) async {
>     logI(sessionConnect.session.pairingTopic, tag: "pairingTopic");
>     launchUrlString("wc:${sessionConnect.session.topic}");
>     var req = await authClient!.request(
>       topic: sessionConnect.session.topic,
>       chainId: "eip155:97",
>       request: SessionRequestParams(
>         method: "wallet_switchEthereumChain",
>         params: [
>           {"chainId": chainIdHex},
>         ],
>       ),
>     );
>     logI(req, tag: ">>>>>>>>>>>>>>>  req");
>   }
> ```

I do this same thing but it doesn't work
```
final signature = await authClient!.request(
        topic: sessionConnect.session.topic,
        chainId: 'eip155:97',
        request: SessionRequestParams(
          method: 'personal_sign',
          params: [{
            "message": "Nonce: ${resNonce.item?.nonce}",
            "address": address ?? "",
          }],
        ),
      );
```

**Comment by AnhTu6610** [comment]
Handling relay close, code: 4010, reason: Disconnecting for load balancing reasons<…> #123

**Comment by nqhhdev** [comment]
@Luzzotica Can you share docs or example `method` for me?

**Comment by ContrastPro** [comment]
Hello everyone! I will briefly describe how to send a transaction through Metamask.

1) Initialize WalletConnect

```dart
  static Web3App? _walletConnect;

  Future<void> _initWalletConnect() async {
    _walletConnect = await Web3App.createInstance(
      projectId: 'c4f79cc821944d9680842e34466bfb',
      metadata: const PairingMetadata(
        name: 'Flutter WalletConnect',
        description: 'Flutter WalletConnect Dapp Example',
        url: 'https://walletconnect.com/',
        icons: [
          'https://walletconnect.com/walletconnect-logo.png',
        ],
      ),
    );
  }
```

2) Create session with Metamask

```dart
  static const String launchError = 'Metamask wallet not installed';
  static const String kShortChainId = 'eip155';
  static const String kFullChainId = 'eip155:80001';

  static String? _url;
  static SessionData? _sessionData;

  String get deepLinkUrl => 'metamask://wc?uri=$_url';

  Future<String?> createSession() async {
    final bool isInstalled = await metamaskIsInstalled();

    if (!isInstalled) {
      return Future.error(launchError);
    }

    if (_walletConnect == null) {
      await _initWalletConnect();
    }

    final ConnectResponse connectResponse = await _walletConnect!.connect(
      requiredNamespaces: {
        kShortChainId: const RequiredNamespace(
          chains: [kFullChainId],
          methods: [
            'eth_sign',
            'eth_signTransaction',
            'eth_sendTransaction',
          ],
          events: [
            'chainChanged',
            'accountsChanged',
          ],
        ),
      },
    );

    final Uri? uri = connectResponse.uri;

    if (uri != null) {
      final String encodedUrl = Uri.encodeComponent('$uri');

      _url = encodedUrl;

      await launchUrlString(
        deepLinkUrl,
        mode: LaunchMode.externalApplication,
      );

      _sessionData = await connectResponse.session.future;

      final String account = NamespaceUtils.getAccount(
        _sessionData!.namespaces.values.first.accounts.first,
      );

      return account;
    }

    return null;
  }
```

3) Create custom EthereumTransaction model

```dart
import 'dart:typed_data';

class EthereumTransaction {
  const EthereumTransaction({
    required this.from,
    required this.to,
    this.value,
    this.data,
  });

  final String from;
  final String to;
  final String? value;
  final Uint8List? data;

  Map<String, dynamic> toJson() => {
        'from': from,
        'to': to,
        'value': value,
        'data': data,
      };
}
```

4) Create instance of EthereumTransaction

```dart
  Future<EthereumTransaction> generateTransaction({
    required String userId,
    required String reseiverId,
  }) async {
    final EthereumTransaction transaction = EthereumTransaction(
      from: userId,
      to: reseiverId,
      value: '1',
    );

    return transaction;
  }
```

5) Sign and send transaction with Metamask

```dart
  Future<Stream<dynamic>?> sendTransaction({
    required EthereumTransaction transaction,
  }) async {
    await launchUrlString(
      deepLinkUrl,
      mode: LaunchMode.externalApplication,
    );

    final Future<dynamic> signResponse = _walletConnect!.request(
      topic: _sessionData!.topic,
      chainId: kFullChainId,
      request: SessionRequestParams(
        method: 'eth_sendTransaction',
        params: [transaction.toJson()],
      ),
    );

    return signResponse.asStream();
  }
```

6) You can check info from request() like this
```dart
      final Stream<dynamic>? stream = await sendTransaction(
        transaction: transaction,
      );

      if (stream != null) {
        stream.listen((event) {
          log('$event', name: 'Stream event');
        });
      }
```

**Comment by nqhhdev** [comment]
@ContrastPro I have some ideas for you. 

1. When will we disconnect and end the session? Once we have created the session, can we create the same session again?
(create multiple sessions by calling `_walletConnect!.connect`)

2. Don't forget that WC has supported multi chain and we have to solve it decide on session management (multi network)

**Comment by nqhhdev** [comment]
@Luzzotica If I haven't added a network to my MM, how will I know?

**Comment by Luzzotica** [comment]
> @Luzzotica If I haven't added a network to my MM, how will I know?

Honestly, I am not sure.
Is this part of the issue though?

I feel like you guys have resolved connecting to MetaMask.

You can reconnect to the same session if you pass the `sessionTopic` into the `_walletConnect!.connect` method. If you do this, there is no need to repair (Scan a QR code), as the pairing and session are already setup for secure communication through the relay.

**Comment by nqhhdev** [comment]
> > @Luzzotica If I haven't added a network to my MM, how will I know?
> 
> Honestly, I am not sure. Is this part of the issue though?
> 
> I feel like you guys have resolved connecting to MetaMask.
> 
> You can reconnect to the same session if you pass the `sessionTopic` into the `_walletConnect!.connect` method. If you do this, there is no need to repair (Scan a QR code), as the pairing and session are already setup for secure communication through the relay.

This case: 
- I use `_walletConnect!.connect` to connect with MM (xyz Network)
- xyz network has not been added to MM
- No errors, still connected to current network and different `chainId`

**Comment by makinghappen** [comment]
@ContrastPro thanks for your example! can you please also share metamaskIsInstalled and launchUrlString implementations?

**Comment by ContrastPro** [comment]
@makinghappen 
1) [launchUrlString](https://pub.dev/documentation/url_launcher/latest/url_launcher_string/url_launcher_string-library.html) method is part of the library [url_launcher](https://pub.dev/packages/url_launcher).

2) [metamaskIsInstalled](https://pub.dev/documentation/external_app_launcher/latest/external_app_launcher/LaunchApp/isAppInstalled.html) method is part of the library  [external_app_launcher](https://pub.dev/packages/external_app_launcher).
```dart
  Future<bool> metamaskIsInstalled() async {
    return await LaunchApp.isAppInstalled(
      iosUrlScheme: 'metamask://',
      androidPackageName: 'io.metamask',
    );
  }
```

**Comment by Luzzotica** [comment]
You can also use the WalletConnectModal library to connect to the wallet with a built in modal.

It has a `launchCurrentWallet` function you can call that will launch the currently connected wallet.

I have just released v2.0.13, which hopefully resolve whatever issues you guys may have been facing with the library.

My tests with the example dapp show me I'm able to connect to metamask and sign txs with it.
Given that fact, and that the discussion here has moved away from metamask connection to launching an app I am going to close this issue as complete.

If you have any other problems, please create a new issue with additional details and information.

**Comment by msalman2890** [comment]
> ```dart
> Future<dynamic>
> ```

@ContrastPro process is stuck on the _walletConnect!.request method. Unable to get anything in the stream.

How can I get transaction hash or I can track it?

**Comment by msalman2890** [comment]
@ContrastPro is it necessary to launch deep link again before request?
