### ISSUE TITLE
How to self-host the relay?

### ISSUE THREAD

**Issue by BrianCliton** [WalletConnect/WalletConnectFlutterV2#115]
How to self-host the relay, is there any open source code for the relay, and supports v2？

**Comment by Luzzotica** [comment]
https://github.com/WalletConnect/relay

You can use this.

Are you wanting to avoid using WalletConnect's relays?
What's your end goal?

**Comment by BrianCliton** [comment]
> https://github.com/WalletConnect/relay

The official relay is unstable. In some areas, https://github.com/WalletConnect/relay is old and does not seem to support flutterV2

**Comment by Luzzotica** [comment]
The official relay is unstable meaning the repo I just sent you is unstable, or the actual hosted relay that we currently connect with is unstable?
What do you mean?

**Comment by Luzzotica** [comment]
There are plans in the future to give you guys the ability to self host a relay. 

As of now though, there isn't a way to do it.

I'm closing this issue.

If you have any other questions on this, perhaps asking them in discord would be better (This is for flutter SDK)
