### ISSUE TITLE
I think there is an abnormal situation that needs to be added to reconnection

### ISSUE THREAD

**Issue by mmMrz** [WalletConnect/WalletConnectFlutterV2#117]
In my use, I often encounter errors from Socket code 1005.
This error will also appear in the Socket connection of Wallet Connect V1
In the specification document of WebSocket, 1005 error is defined as an unexpected interrupt, and I believe this situation should be added to the reconnection mechanism:
https://www.rfc-editor.org/rfc/rfc6455#section -7.4

The modified content is shown in the screenshot
![need modify](https://github.com/WalletConnect/WalletConnectFlutterV2/assets/8433872/0dd71f19-4b7a-41f0-bd06-85702a1fabfe)
This code has been tested and added locally, solving the above problems and greatly improving stability

The frequency of this error code is extremely high in the connection between my country's network and WalletConnect relay server.

Thank you for your contribution

**Comment by mmMrz** [comment]
Currently, I have used a method to reconnect to fix this error
As shown in the following screenshot:
![current fix](https://github.com/WalletConnect/WalletConnectFlutterV2/assets/8433872/94a8047f-eaed-4390-a63c-1c6dbb9dd0eb)
If my approach does not meet your design specifications or is unreasonable, please let me know. Thank you very much.

**Comment by Luzzotica** [comment]
I'm reaching out to the relay team at WalletConnect to determine what this code is.

If I know what it is, and it makes sense to add it to the autoreconnect functionality, I will do so.
