### ISSUE TITLE
https://magiceden.io/ return null icons in pairingMetada json

### ISSUE THREAD

**Issue by r-oman-G** [WalletConnect/WalletConnectFlutterV2#119]
<img width="925" alt="ScreenShot 2023-06-29 at 13 14 53@2x" src="https://github.com/WalletConnect/WalletConnectFlutterV2/assets/38914451/bf298abd-c5ef-4d0c-b42f-0a4e46cd2757">

It throw null exception on parsing

**Comment by Luzzotica** [comment]
Looking into it.

I don't think the icons is a nullable field. We recommend that all dApps and wallets have it. Which is why it's required in the javascript monorepo:

```javascript
interface Metadata {
    name: string;
    description: string;
    url: string;
    icons: string[];
    verifyUrl?: string;
    redirect?: {
      native?: string;
      universal?: string;
    };
  }
```

**Comment by Luzzotica** [comment]
It is a magiceden problem.

The icons should never be null in the JSON object.

They can be empty, but not null.
