### ISSUE TITLE
Errors for initialising WebSocket

### ISSUE THREAD

**Issue by crypblizz8** [WalletConnect/WalletConnectFlutterV2#120]
Post on behalf of [SupaCharge](https://twitter.com/supachargeio?lang=en) team

We (WalletConnect) have been provided the information:

**Version of package:** 
walletconnect_flutter_v2: ^2.0.10

**Provide the reproduction path for this issue:** 
1) IOS clicking on metamask launches the application but no request to connect or sign. For trust wallet it says connecting to walletconnect indefinitely. 
2) Android. We tested on 3 different physical devices. When clicking connect nothing pops up. 
3) you can test it at https://supacharge.io/download

The wallet (platform - iOS or Android and version) you are using to get to this error
- Not Provided

Errors running into:
![telegram-cloud-photo-size-5-6102524800036616248-y](https://github.com/WalletConnect/WalletConnectFlutterV2/assets/45455218/38bdf693-d4d9-4dd0-a779-893cfaf3704a)

**Comment by Luzzotica** [comment]
Are they using the Web3Modal package I have been developing or are they trying to build this from scratch themselves?

Also, 2.0.12 is out, please have them update to the newest version and then let me know if there are issues.

**Comment by Luzzotica** [comment]
Closing this as it's rather stale.
