### ISSUE TITLE
how can contact with erc20 contract to send tokens from two address

### ISSUE THREAD

**Issue by ArDapps** [WalletConnect/WalletConnectFlutterV2#124]
how can contact with erc20 contract to send tokens from two address

**Comment by Jens05** [comment]
Erc20 contracts arent supported i believe, only simple calls. If there is a way that we can obtain credentials with this library (just like the old one) then everybody can use web3dart's transaction.callcontract like normal. Maybe @Luzzotica can assist us further...

**Comment by ArDapps** [comment]
NEED WAY TO GET THE CRIDENTIALS OR OTHER WAY TO CALL ABI


<img width="1455" alt="Screenshot 2023-07-04 at 2 12 45 PM" src="https://github.com/WalletConnect/WalletConnectFlutterV2/assets/91119772/7bf92347-d4cd-4c96-a4bb-6acb27f8fcd6">

**Comment by jay-benzatine** [comment]
@Jens05 @ArDapps 

Hello,

I have given this issue solution already into the #122

**Comment by Luzzotica** [comment]
@jay-benzatine Is correct, he resolved it in his issue above.

There is also an example of sending a transaction to MetaMask to be signed in the dapp example. It doesn't leverage an existing contract, but you should be able to built a Transaction that does using something like Web3Dart.
