### ISSUE TITLE
How to know whether WebSocket is died

### ISSUE THREAD

**Issue by devLoganHere** [WalletConnect/WalletConnectFlutterV2#127]
Sometimes android/ios operating systems make the app idle, so the WebSocket connections die
e.g. When the app is switched to the background from the foreground.
e.g. When the app is not being used for a long time, even in the foreground.

There are obvious ways to catch the above cases and consider them, but It should be provided how to check WebSocket status.
If WebSocket is dead, we can call `core.relayClient.connect()` to reconnect.

How to know the status?

**Comment by Luzzotica** [comment]
I will add a bool you can use to get the current connection status.

You can call the `core.relayClient.connect` function to reconnect to the relay.

There is also a heartbeat that should be reconnecting it, but that might get canceled when the app enters the background.

**Comment by devLoganHere** [comment]
Thanks a lot. A bool of status will be useful to deal with WebSocket connection.

Should I reconnect a heartbeat you mentioned? I'm wondering whether `core.relayClient.connect`includes reconnecting it.

**Comment by Luzzotica** [comment]
Resolved with v2.0.13

The `relayClient.isConnected` is your bool.
