### ISSUE TITLE
Disconnected from dapp and the topic received by the onSessionDelete method of walletApp is not the topic

### ISSUE THREAD

**Issue by gujiavv** [WalletConnect/WalletConnectFlutterV2#128]
I disconnected from dapp and the topic received by the onSessionDelete method of walletApp is not the topic I established the connection with. What is the reason? I need to listen to Dapp and disconnect, and then my walletApp needs to clean up local data

**Comment by Luzzotica** [comment]
There is a pairing topic and a session topic.

You can disconnect the session using either.

The pairing is established first, and then the pairing is used to create a session that can be used to sign transactions with the wallet.

It is likely that you stored the pairingTopic and not the session topic and that that is why they do not match up.

Let me know if that's the case or if you have any other issues.
