### ISSUE TITLE
Error while creating Web3Wallet instance

### ISSUE THREAD

**Issue by phuocbitmark** [WalletConnect/WalletConnectFlutterV2#129]
Hi, i'm trying using the pub on my wallet app and got this error while calling await Web3Wallet.createInstance().
I did download the example, build it on my phone (GalaxyNote9) but the same error happened, and i couldn't connect to ens using the example app
RelayClient._createJsonRPCProvider (package:walletconnect_flutter_v2/apis/core/relay_client/relay_client.dart:235:19)
asynchronous suspension>

Initializing WebSocket with wss://relay.walletconnect.com?auth=eyJhbGciO...fQ.BkdJOE960Z1zD7zIyG7bthMV-uM2qov_57-40PcA90J_4gJ4y8rrBVSTTZYpSxqCyEvugZedwCa_SMiog9F-BQ&ua=wc-2%2FFlutter-2.0.12%2Fandroid-QP1A.190711.020.N960FXXU9FVG2%2Fandroid

**Comment by Luzzotica** [comment]
Do you have a valid project ID?

**Comment by phuocbitmark** [comment]
Yes, i do. I tried to ignore it and continue, it still worked. i guess it's just a warning.

But i also encounter another problem. I work on wallet side, when i approve session proposal (.approveSession), it take too long, and it returns (with topic) to me much later than the dapp side, so if the dapp send to wallet a sign request right away, it even comes before the approveSession call finish

**Comment by Luzzotica** [comment]
Create a different issue for your above problem.
