### ISSUE TITLE
Question - When a session topic has two accounts,  how do you specify which to use?

### ISSUE THREAD

**Issue by bobwith2bees** [WalletConnect/WalletConnectFlutterV2#131]
Lower priority question, but I am trying to understand some design corner cases.

WalletConnect V2 allows you to negotiate a pairing session and a single session topic can include multiple wallets on the same chainId.  
```
sessionTopic 8881d5087cd00d02a1ea93a37997f6dca15b7e3ba3bb0a4b5d41738437baf319 - accounts: [Ethereum 0xbae9...bbee, Ethereum 0x9d15...00d9]
```

If I call the sign client to send a transaction (eth_sendTransaction), how do I specify which of the two accounts I want to use (e.g. which account pays gas)?  The calling parameter is only asking for a session topic and chain Id.  

/lib/apis/sign_api/sign_client.dart
```dart
  Future request({
    required String topic,
    required String chainId,
    required SessionRequestParams request,  // has String method and dynamic params
```

Is the wallet responsible for prompting the user to select?  Or determine from the method parameters which wallet applies (peeking at the from:?)   Just trying to understand the WalletConnect design and user experience.

**Comment by Luzzotica** [comment]
Generally when you send in a transaction it includes the account that will execute that transaction, no?

SImplest example: Sending tokens. From, To. From will use one account, and the wallet will recognize that and sign with it.

If the account isn't in the transaction, then I honestly have no idea. That was the assumption I have always worked under.
Two options:
1. Transactions will get more explicit (Gas payer and From will be separate), or
2. Wallet will ask the user which account to pay gas from.

I suspect we will eventually use both of these.

**Comment by bobwith2bees** [comment]
Thanks for the info.  I'll close this issue as it's more of a higher level WalletConnect protocol and compatibility discussion.   

I haven't seen any documentation guiding wallets that they should cover this corner case.  I just wanted to make sure I was a well behaved DAPP ;-)
