### ISSUE TITLE
examples outdated, requiredNamespaces require a "events" named parameter.

### ISSUE THREAD

**Issue by makinghappen** [WalletConnect/WalletConnectFlutterV2#133]
https://github.com/WalletConnect/WalletConnectFlutterV2#dapp-flow

requiredNamespaces require a "events" named parameter.

ConnectResponse resp = await signClient.connect(
    requiredNamespaces: {
        'eip155': RequiredNamespace(
            chains: ['eip155:1'], // Ethereum chain
            methods: ['eth_signTransaction'], // Requestable Methods
        ),
        'kadena': RequiredNamespace(
            chains: ['kadena:mainnet01'], // Kadena chain
            methods: ['kadena_quicksign_v1'], // Requestable Methods
        ),
    }
);

**Comment by Luzzotica** [comment]
Resolved with v2.0.13
