### ISSUE TITLE
There is no pullback when smart contract coins are converted to ether

### ISSUE THREAD

**Issue by gzios** [WalletConnect/WalletConnectFlutterV2#134]
When using  [walletconnect_flutter_v2: ^2.0.12](https://github.com/WalletConnect/WalletConnectFlutterV2/releases/tag/v2.0.12), I found that there is no callback when converting smart contract currency to Ethereum, and Ethereum conversion to smart contract currency is normal. I don't know if I am the only one who has this problem when using [uniswap](https://app.uniswap.org/#/swap).

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.4.1 22F82 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.2)
[✓] VS Code (version 1.79.2)
[✓] Connected device (2 available)
    ! Error: iPhone is busy: Fetching debug symbols for iPhone. Xcode will continue when iPhone is finished. (code -10)
[✓] Network resources
```

**Comment by Luzzotica** [comment]
Is there a WC request you are making for this to the connected wallet?

That's what I assume when you say "callback".

I am highly unfamiliar with EVM development and the available functions. I need a bit more context before I can help you.

**Comment by gzios** [comment]
> Is there a WC request you are making for this to the connected wallet?
> 
> That's what I assume when you say "callback".
> 
> I am highly unfamiliar with EVM development and the available functions. I need a bit more context before I can help you.

It is an interaction issue that has already been connected. I found in the new test that it is not an issue with the SDK. But [uniswap](https://app.uniswap.org/#/swap) Caused by. Because other EVM can be used normally. Therefore, this issue can be closed. Thank you very much for your reply
