### ISSUE TITLE
How to identify wallet's current account and chainId ? 

### ISSUE THREAD

**Issue by mthinh** [WalletConnect/WalletConnectFlutterV2#138]
I'm developing a decentralized application (dApp) that integrates with the Metamask wallet. After establishing a connection, I can obtain the current chainId and account details, and also subscribe to 'accountChanged' and 'chainsChanged' to keep these details updated.
However, I'm encountering a problem when the app is closed and restarted. I'm unsure how to determine the account and chainId that the wallet is currently using, because the event subscription doesn't activate when the Web3App initializes for the first time.

Here's why it's necessary: Let's say I connect to the account eip155:5:address, but then my wallet switches to eip155:1:address or eip155:1:other_address. Now, if I want to send a message request for signing from my dApp, the wallet app won't show the sign message popup unless I specify the current chainId and address of the wallet app.

Hence, I need this information to alert users to switch to the correct chainId and account address.

I'm using metamask for experimental

**Comment by AmjadKhan2k18** [comment]
@mthinh 

https://docs.metamask.io/wallet/reference/eth_chainId/

in WalletConnect V1 I used eth_chainId to get current chain from metamask

and wallet_switchEthereumChain method to switch chain 

but right now there are bugs related to switch chain method in Metamask github so I am not sure if it is fully functional in latest version

**Comment by mthinh** [comment]
@AmjadKhan2k18 do you have issue link ? can you share me ?

**Comment by AmjadKhan2k18** [comment]
@mthinh  here it is  https://github.com/MetaMask/metamask-mobile/issues/6655

**Comment by Luzzotica** [comment]
Not sure if I have anything else to input here.

Sounds like ethereum just needs codified methods for you to fetch the current chain info and request it be changed if necessary.

Closing as complete.
