### ISSUE TITLE
Can not parse message to sign transaction

### ISSUE THREAD

**Issue by cimsunf0702** [WalletConnect/WalletConnectFlutterV2#139]
I'm trying to parse the message from eth_sign call back, but got exception in parse (EthUtils.getUtf8Message) method. Anyone have same issue and got solution ? thank you !

```
     web3Wallet.registerRequestHandler(
          chainId: 'eip155:$chainId',
          method: 'eth_sign',
          handler: (topic, parameters) {

            //parameters[1] = '0xfd8815a699829762de4756f9602437fa558935005867bb525e58d1c96e241d1a'
            final message = EthUtils.getUtf8Message(parameters[1]);
      });
```

**Comment by Luzzotica** [comment]
What dapp are you interacting with?

**Comment by cimsunf0702** [comment]
I found out solution: register handler for "eth_signTypedData_v4" -> the call back will replace "eth_sign" with readable data. thanks.
