### ISSUE TITLE
How to match events in `onSessionEvent` callback?

### ISSUE THREAD

**Issue by SametSahin10** [WalletConnect/WalletConnectFlutterV2#14]
How do we match events in an `onSessionEvent` callback? Let's say I'd like to respond to `eth_sign` event. In `SessionEvent` class, there isn't a field called `method` or similar. I was thinking about using the value of a field in `onSessionEvent` and have a switch-case that switches on that field. Is `registerEventHandler` should be used to register and event handler for this? Our app is a wallet app.

On WalletConnect V1, we were using this [package](https://pub.dev/packages/wallet_connect). We were providing a callback to `onEthSign` like below. I'm looking for the equivalent in your package.

```
final wcClient = WCClient(
      onConnect: () {
        // Respond to connect callback
      },
      onDisconnect: (code, reason) {
        // Respond to disconnect callback
      },
      onFailure: (error) {
        // Respond to connection failure callback
      },
      onSessionRequest: (id, peerMeta) {
        // Respond to connection request callback
      },
      onEthSign: (id, message) {
        // Respond to personal_sign or eth_sign or eth_signTypedData request callback
      },
      onEthSendTransaction: (id, tx) {
        // Respond to eth_sendTransaction request callback
      },
      onEthSignTransaction: (id, tx) {
        // Respond to eth_signTransaction request callback
      },
    );
```

**Comment by Luzzotica** [comment]
WalletConnect v2 has generalized the chain interaction so that it doesn't work only with EVM based chains.
This means that there won't be any functions in the library itself that reference a particular chain.

Please read the [documentation](https://docs.walletconnect.com/2.0/advanced/migrating-from-v1.0) on how to migrate from v1 to v2.

**Comment by SametSahin10** [comment]
I see. So, if we were to listen for an event that is fired by an EVM based chain, say `eth_sign`, We would register an event handler like below:

```
wcClient.registerEventHandler(
  // "eth" is a placeholder.
  namespace: 'eth',
  method: 'eth_sign',
);
```

Is this correct?

**Comment by Luzzotica** [comment]
As per the readme, this is how you would register and listen to events:
```dart
// You can also respond to events from the wallet, like session events
wcClient.onSessionEvent.subscribe((SessionEvent? session) {
  // Do something with the event
});
wcClient.registerEventHandler(
  namespace: 'kadena',
  event: 'kadena_transaction_updated',
);
```
