### ISSUE TITLE
richer examples, metamask conenction, integration with web3 library

### ISSUE THREAD

**Issue by makinghappen** [WalletConnect/WalletConnectFlutterV2#140]
in another issue [@contrastpro](https://github.com/ContrastPro) have provided a working example for metamask connection
https://github.com/WalletConnect/WalletConnectFlutterV2/issues/113#issuecomment-1620083931

and [@4xMafole](https://github.com/4xMafole) provided an example for integration with [web3 dart library](https://github.com/devopsdao/webthree)
https://github.com/WalletConnect/WalletConnectFlutterV2/issues/122#issuecomment-1632359925

Can it be integrated into the examples so new users would easily find it and also it would be maintained in case of API changes?

**Comment by Luzzotica** [comment]
Thank you for the issue!

I will be building out the working examples next week and combining them with the WalletConnectModal example.

As such, [here's](https://github.com/WalletConnect/Web3ModalFlutter/issues/15) this same issue over there.
