### ISSUE TITLE
WalletConnect not auto-navigating/redirecting back to my app after personal_sign request approval from rainbow wallet 

### ISSUE THREAD

**Issue by Rohitbagul003** [WalletConnect/WalletConnectFlutterV2#142]
When i connect with rainbow and initiate personal_sign after approving the request its not navigating me back to my app

It redirect when i sign with TrustWallet 

here is the function:- 
`
```dart
try {
      await launchUrl(Uri.parse(uri.toString()), mode: LaunchMode.externalNonBrowserApplication);
      List<String?> params = [message, account];
      final dynamic signResponse = await web3app.request(
        topic: ses.topic,
        chainId: 'eip155:1',
        request: SessionRequestParams(
          method: 'personal_sign',
          params: params,
        ),
      );
      debugPrint("ses.topic ----> ${ses.topic}");
      debugPrint("signResponse ---> $signResponse");
      signature = signResponse;
    } catch (err) {
      debugPrint("error in wallet connect sign ---> $err");
      signature = "";
      await onSignFailed();
    }
``` 
```[tasklist]
### Tasks
```

**Comment by Luzzotica** [comment]
I have no control over whether or not Raindbow redirects back to your app.

Please create an issue on their github if possible.

**Comment by samuelezedi** [comment]
same thing happens with Metamask.

**Comment by Rohitbagul003** [comment]
But for me Metamask navigates me back to my app
My device samsung galaxy j6
Android 10

**Comment by bobwith2bees** [comment]
@Rohitbagul003  @samuelezedi 

Do either of you have the optional redirect field populated in your PairingMetadata that you send to the wallet?   Is the redirect URI registered with IOS so the wallet can call the deep link and return to the proper screen on your app?

The protocol supports this, but I have no actual experience if any of the wallet apps are leveraging this optional field.   

And as @Luzzotica mentioned - interop issues should be covered elsewhere.
