### ISSUE TITLE
If i connect with trustWallet it works but when i request sign sometimes it gives me an error

### ISSUE THREAD

**Issue by Rohitbagul003** [WalletConnect/WalletConnectFlutterV2#143]
When i connect for the first time and request personal_sign it works ..
but when i try to reconnect and do sign again it doesnt work....
The reconnect works everytime but the sign doesnt, and throw this error:-
`JsonRpcError(code: 5300, message: Invalid Session Properties requested)`

**Comment by Luzzotica** [comment]
Do you have any additional details?

Like, does the sign request pop up in trust wallet on the second reconnect?

When you say "reconnect" what exactly do you mean?

**Comment by Rohitbagul003** [comment]
"reconnect - connect and signing a personal_sign then disconnecting and repeating the process again.."

Also sometimes when i connect using TrustWallet it gets connected and redirect me back to my app without returning the `session.future` i need to go back to trustWallet again manually after that i it returns `session.future`

**Comment by Rohitbagul003** [comment]
Am working on Android 10
the device is Samsung Galaxy J6

**Comment by Luzzotica** [comment]
Working with WalletConnectModal I haven't run into this issue. My guess is that you're passing in a SessionProperties, but Trust Wallet isn't ok with the options you provided.

I am closing this as resolved.

I suggest upgrading to WalletConnectModal to resolve this issue.
