### ISSUE TITLE
Integrate with installed wallets

### ISSUE THREAD

**Issue by Hardu2203** [WalletConnect/WalletConnectFlutterV2#144]
Is there plans to just integrate with installed wallets directly, instead of connecting via QR code?

**Comment by Luzzotica** [comment]
Assuming you are talking about launching installed wallets on a mobile device directly, you can do that with [WalletConnectModal](https://pub.dev/packages/walletconnect_modal_flutter)

The modal does not yet work on web or desktop, but it will eventually.
