### ISSUE TITLE
Select account

### ISSUE THREAD

**Issue by YannMarti** [WalletConnect/WalletConnectFlutterV2#147]
Hey, Im currently trying to integrate WC in a Wallet im working on. It is multiwallet, so i would like the user to be able to choose with which account he wants to connect to the page. How can i select a certain wallet that should be connected? If i register all the accounts beforehand it will just list all wallets as connected, but if i only want to register the wallet once _onSessionProposal is called and th user selected it, then it obiously doesnt do anything since args.params.generatedNamespaces does not get updated. Do i have to create my own namespaces manually?

**Comment by Luzzotica** [comment]
If you want to request access to multiple chains, you will have to design your namespaces manually, yes.

I do not know if every wallet will support multichain functionality, but WalletConnect v2 does.
