### ISSUE TITLE
Do not show popup to sign

### ISSUE THREAD

**Issue by nqhhdev** [WalletConnect/WalletConnectFlutterV2#149]
### DES
- This is my code, when I request `eth_signTransaction` on Metamask can't show pop to sign. 

```
await _signClient!.request(
        topic :sessionData!.first.topic,
        chainId: 'eip155:1',
        request: SessionRequestParams(
            method: 'eth_signTransaction',
            params: [anything]
        ),
      );
```

```
[log] JsonRpcError(code: 5000, message: {"code":-32004,"message":"Method not supported."})
```

**Comment by nqhhdev** [comment]
@Luzzotica Any update?

**Comment by Luzzotica** [comment]
`Method not supported` means that the wallet doesn't support the `eth_signTransaction` method.

You could try `eth_sendTransaction`.

Other than that, I cannot help you here.
If you want the wallet to support that method, you will have to reach out to them directly.
