### ISSUE TITLE
WalletConnectError - (code: 5101, message: Unsupported methods / Unsupported chains.)

### ISSUE THREAD

**Issue by huantd0111** [WalletConnect/WalletConnectFlutterV2#151]
### Encountering Problems When Pairing with DApp using walletconnect_flutter_v2

I am using the walletconnect_flutter_v2 library to connect my application with a decentralized app (DApp). However, when I call the pair(uri: Uri.parse(url)) function, I am not receiving the onSessionProposal or onAuthRequest events. During the process, I encountered the following error log:

`error: WalletConnectError(code: 5100, message: Unsupported chains. onSessionProposeRequest namespaces chains don't satisfy requiredNamespaces chains for eip155, data: null)`

```
flutter: My Wallet: connect https://react-app.walletconnect.com/
flutter: My Wallet: WalletConnectV2Utils: _onPairingsSync Instance of 'StoreSyncEvent'
flutter: My Wallet: WalletConnectV2Utils: _onPairingCreate PairingEvent(id: null, topic: 80821daca1ebdca06ca0c3b07443c063f9e22e7e604e688b965274be885d1843, error: null)

flutter: My Wallet: WalletConnectV2Utils: _onSessionProposalError SessionProposalErrorEvent(id: 1689759861542592, requiredNamespaces: {eip155: RequiredNamespace(chains: [eip155:5], methods: [eth_sendTransaction, personal_sign], events: [chainChanged, accountsChanged])}, namespaces: {eip155: Namespace(accounts: [eip155:5:0xe2270d1361dc3fbe9765cd60a329f8b3042ed8db], methods: [], events: [])}, error: WalletConnectError(code: 5101, message: Unsupported methods. onSessionProposeRequest namespaces methods don't satisfy requiredNamespaces methods for eip155, data: null))

flutter: My Wallet: WalletConnectV2Utils: _onPairingsSync Instance of 'StoreSyncEvent'
flutter: My Wallet: WalletConnectV2Utils: _onPairingCreate PairingEvent(id: null, topic: 9289deefe406009d69f7577541f51e8e03c9f459b11d70a531f72c3518020cd8, error: null)
flutter: My Wallet: WalletConnectV2Utils: _onSessionProposalError SessionProposalErrorEvent(id: 1689759994990866, requiredNamespaces: {eip155: RequiredNamespace(chains: [eip155:56], methods: [eth_sendTransaction, personal_sign], events: [chainChanged, accountsChanged])}, namespaces: {eip155: Namespace(accounts: [eip155:5:0xe2270d1361dc3fbe9765cd60a329f8b3042ed8db], methods: [], events: [])}, error: WalletConnectError(code: 5100, message: Unsupported chains. onSessionProposeRequest namespaces chains don't satisfy requiredNamespaces chains for eip155, data: null))
```

Steps to Reproduce
openDApp : https://react-app.walletconnect.com/
click choice Ethereum Goerli and Connect
Call the pair(uri: Uri.parse(url)) function to connect with a DApp.
Check the log to see the reported error.
Environment
walletconnect_flutter_v2 version: [package and specific version]
Operating System: IOS Simulator 16.4
Flutter Version: 3.10.5

**Comment by flutterdevcodiste** [comment]
I can something relate to your situation. 

I'm encountering the same error while attempting to connect [opensea.io](opensea.io) with WCv2 using the shared code from a wallet demo app. 
The error message I'm receiving from [opensea.io](opensea.io) was: "Unsupported methods. The onSessionProposeRequest namespaces methods do not meet the requiredNamespaces methods for eip155".

**Comment by huongse7en** [comment]
I'm having the same problem, did you find a solution?

**Comment by Rohitbagul003** [comment]
with the below code i was able to connect with Metamask, rainbow etc.

Hope this helps ... 

```dart
ConnectResponse? resp = await web3app?.connect(requiredNamespaces: {
        'eip155': const RequiredNamespace(
          chains: ["eip155:1"], // Ethereum chain
          methods: ['personal_sign', 'eth_sign', 'eth_sendTransaction'], // Requestable Methods
          events: ["chainChanged", "accountsChanged"], // Requestable Events
        )
      });

      uri = resp?.uri;
      url = uri.toString();
      if (deepLink != null) {
        final link = formatNativeUrl(deepLink, uri.toString());
        url = link.toString();
      }
      await launchUrl(Uri.parse(url.toString()), mode: LaunchMode.externalNonBrowserApplication);

      debugPrint("returning the wallet response $url");
      ses = (await resp?.session.future);
      log("SessionData ----> ${ses.toString()}");

      final String address = NamespaceUtils.getAccount(
        ses?.namespaces.values.first.accounts.first ?? "",
      );
```

**Comment by Luzzotica** [comment]
So the issue here is that you haven't told the WC library which chains and methods you support, or you don't support the methods requested by the dApp.

So when it receives a request, it checks the requiredNamespaces of that request, validates it against the available data (that you've given the library) and if it can, it will construct the proper response for the requested information it will do it for you automatically.

If it cannot construct it it will throw the above error.

You can resolve this by adding Goerli as a supported chain with all of the methods it requires.

I thought I had added this information to the docs but I obviously haven't. I will do that today and close this issue when I do.

**Comment by Luzzotica** [comment]
I have updated the readme with info on how to setup automated namespace handling.
