### ISSUE TITLE
Is it possible to change chain id in dapp ?Is it possible to get balance of the wallet in the dapp?

### ISSUE THREAD

**Issue by sam-dev-1729** [WalletConnect/WalletConnectFlutterV2#154]
I have a dapp that developed by flutter . I need these to options in below: 
1. change chain id  2 . display the balance
For example, I connected to the wallet with chain id like eip155:1 , It is possible to change the chain ID without kill session and  then create a smart contract with the new chain ID.
 
I am sending only one chain ID  in the required namespace like this [ eip155:1] ,and I don't want to send a list like this [ eip155:1 ,eip155:56] .
one more question : Is it possible to display the balance of the wallet in the dapp?

**Comment by Luzzotica** [comment]
1. You can kill the session and request that a new one is created on the same pairing as before.

So, save the pairingTopic.
Delete the session using the session topic.
Call connect using the pairing topic you already had.

I don't promise that every wallet will support deleting a session but not the pairing (they might delete the pairing along with it) but you can give it a shot!

2. the wallet gives you back an address. You can query infura or something else using Web3Dart to get the balance of that address.
