### ISSUE TITLE
Issue with Swap Transaction Signing using WalletConnect V2 in Uniswap and PancakeSwap

### ISSUE THREAD

**Issue by flutterdevcodiste** [WalletConnect/WalletConnectFlutterV2#155]
I'm facing an issue with swap transactions on Uniswap and PancakeSwap. The problem is related to properly signing transactions using WalletConnect V2, both in my app and the provided wallet demo app in the library.

I've been trying to find a solution for the past two to three days but haven't been successful. It would be really helpful if you could assist me with this issue and provide guidance on how to sign transactions.

**Comment by flutterdevcodiste** [comment]
Thanks @AmjadKhan2k18  for the instant reply,

I have understood your suggestion, but I have a question: If I try to do this manually, then what is the use of the library demo of the wallet?

I tried the following steps using the wallet demo code:

Register event method 

```
 wallet.registerRequestHandler(
      chainId: getChainId(),
      method: eSignTransaction,
      handler: ethSignTransaction,
    );
```

Converted Ethereum transaction to Web3 transaction format geting from ethSignTransaction params.

```
     EthereumTransaction ethTransaction = EthereumTransaction.fromJson(
        parameters[0],
      );

final transaction = Transaction(
        from: EthereumAddress.fromHex(ethTransaction.from),
        to: EthereumAddress.fromHex(ethTransaction.to ?? ""),
        value: EtherAmount.fromBigInt(
          EtherUnit.wei,
          BigInt.tryParse(ethTransaction.value) ?? BigInt.zero,
        ),
        gasPrice: ethTransaction.gasPrice != null
            ? EtherAmount.fromBigInt(
                EtherUnit.gwei,
                BigInt.tryParse(ethTransaction.gasPrice ?? "0") ?? BigInt.zero,
              )
            : null,
        maxFeePerGas: ethTransaction.maxFeePerGas != null
            ? EtherAmount.fromBigInt(
                EtherUnit.gwei,
                BigInt.tryParse(ethTransaction.maxFeePerGas ?? "0") ?? BigInt.zero,
              )
            : null,
        maxPriorityFeePerGas: ethTransaction.maxPriorityFeePerGas != null
            ? EtherAmount.fromBigInt(
                EtherUnit.gwei,
                BigInt.tryParse(ethTransaction.maxPriorityFeePerGas ?? "0") ?? BigInt.zero,
              )
            : null,
        maxGas: ethTransaction.gasLimit != null ? int.tryParse(ethTransaction.gasLimit!) : null,
        data: (ethTransaction.data != null && ethTransaction.data != '0x')
            ? hexToBytes(ethTransaction.data ?? "")
            : null,
        nonce: ethTransaction.nonce != null ? int.tryParse(ethTransaction.nonce!) : null,
      );
      
```

Tried to sign the transaction using the chain ID and a specific method.

```
final Uint8List sig = await ethClient.signTransaction(
        credentials,
        transaction,
        chainId: chainId,
      );
```

Returned the hash value to the WalletConnect library in ethSignTransaction handler.

```
final String signedTx = hex.encode(sig);
return '0x$signedTx';
```

Could you please check and let me know where I might be wrong? 
Is it compulsory to try manually and not use the demo?

**Comment by Luzzotica** [comment]
He isn't doing it manually. 

You could request the approve method from the dApp as well, he's just saying you have to ensure that approve is called for the address before you execute the swap.

Your code looks fine to me.

You haven't provided a single error log or any information on what is going wrong so I cannot help you.

Please provide error logs and precise information on where your flow is breaking or I will close this issue.

**Comment by mHassan20896** [comment]
```
final Credentials credentials = EthPrivateKey.fromHex(_privateAddress);

    EthereumTransaction ethTransaction =
        EthereumTransaction.fromJson(parameters[0]);

    final transaction = Transaction(
      from: EthereumAddress.fromHex(ethTransaction.from),
      to: EthereumAddress.fromHex(ethTransaction.to),
      value: EtherAmount.fromBigInt(
        EtherUnit.wei,
        BigInt.parse(ethTransaction.value!.substring(2), radix: 16),
      ),
      gasPrice: ethTransaction.gas != null
          ? EtherAmount.fromBigInt(
              EtherUnit.wei,
              BigInt.tryParse(ethTransaction.gas!, radix: 16) ?? BigInt.zero,
            )
          : null,
      data: (ethTransaction.data != null && ethTransaction.data != '0x')
          ? Uint8List.fromList(hex.decode(ethTransaction.data!.substring(2)))
          : null,
    );

    try {
      final Uint8List sig = await ethClient.signTransaction(
        credentials,
        transaction,
      );
      final String signedTx = hex.encode(sig);

      // Return the signed transaction as a hexadecimal string
      return '0x$signedTx';
```
      
I have this piece of code in "eth_sendTransaction", but it fails on Uniswap

**Comment by mHassan20896** [comment]
flutter: \^[[38;5;196m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
flutter: \^[[38;5;196m│ ⛔ [SignEngine] _getVerifyContext<…>
flutter: \^[[38;5;196m└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>

**Comment by quetool** [comment]
Hello @mHassan20896, you can disregard _getVerifyContext error, it just mean the dapp couldn't be verified. Regarding your previous message please open a new issue with proper steps to reproduce it.
