### ISSUE TITLE
Missing automatically disconnected wallet from dApp website

### ISSUE THREAD

**Issue by flutterdevcodiste** [WalletConnect/WalletConnectFlutterV2#157]
Hi 
In WalletConnect Version 1, when we disconnect the dApp from the wallet, it instantly updates in the dApp website (like Uniswap) and removes the wallet from the connection. However, in Version 2, I haven't found this feature yet. Can you please suggest how to achieve this in Version 2? If it's not currently available in Version 2, please consider adding it to your future plans.

**Comment by Luzzotica** [comment]
If you delete a session in the wallet it should delete it in the dapp.

If this is not the case, then the dapp hasn't been setup to respond to the deletion of the session or pairing.

I would suggest creating an issue on the dapp that isn't responding to the deletion event and asking them to fix it.

**Comment by johnsonejezie** [comment]
> Hello,
> 
> I recently experimented with TrustWallet in WC with both PancakeSwap and Uniswap. During my testing, I noticed that TrustWallet works as expected with disconnected from the app, and the respective site also disconnected automatically.
> 
> However, I encountered an issue when disconnecting from my app; it appears that the wallet connection to PancakeSwap and Uniswap is not removed. This behavior indicates that there might be a missing step or configuration on the wallet's side.
> 
> I followed the instructions provided in the README file and integrated the code as directed into my application. Unfortunately, despite following the provided steps, the disconnection functionality is not functioning as anticipated.
> 
> Could you kindly suggest the correct location within the codebase where I need to add the disconnection logic? I am interested in ensuring a smooth disconnection process that properly maintains the wallet's connection status in both PancakeSwap and Uniswap.

Make sure you are disconnecting session topic and not pairing topic
