### ISSUE TITLE
Does not go back to Dapp after signing.

### ISSUE THREAD

**Issue by samuelezedi** [WalletConnect/WalletConnectFlutterV2#162]
Hey, I can connect on iOS and sign in, but after signing in, it does not go back to my app. But it goes back on Android. There something i need to do for iOS

**Comment by devLoganHere** [comment]
@samuelezedi,

I'm trying to integrate wallet connect v2 using the mobile link (deep link / universal link) on our wallet.
There's no document to achieve this with the WalletConnectFlutter. It only exists a case of using the QR code.

Could you share with me any hints to get this?
I guess I should put the WC URI that comes from the mobile link to the pairing function. Is this an acceptable approach?

**Comment by Luzzotica** [comment]
@samuelezedi If it isn't returning on iOS then the wallet needs to update their app to return to the previous app on iOS.
You could also add in the proper `redirect` for your app into the PairingMetadata when you create the WalletConnect client to make it easier for the wallet to redirect back properly.

@devLoganHere If you want easy deep linking, use the [WalletConnectModal](https://pub.dev/packages/walletconnect_modal_flutter) package.
