### ISSUE TITLE
How to integrate WalletConnectFlutter v2 using mobile link on the wallet

### ISSUE THREAD

**Issue by devLoganHere** [WalletConnect/WalletConnectFlutterV2#163]
I'm trying to integrate wallet connect v2 using the mobile link (deep link / universal link) on our wallet.
But there's no document to achieve this with the WalletConnectFlutter. It only exists a case of using the QR code.

Please let me know any hints to get this.
I guess I should put the WC URI that comes from the mobile link to the pairing function. Not sure this is the right approach.

**Comment by AmjadKhan2k18** [comment]
@devLoganHere  you will need deeplink or  universal link  of wallet + wc?uri= + uri you get from connect method

for example for metamask metamask://wc?uri=${uri}

or you can use https://pub.dev/packages/walletconnect_modal_flutter

**Comment by devLoganHere** [comment]
@AmjadKhan2k18, Thanks for the comment!
Once I get the WC URI from them, how could I use it on the wallet side?
Should I put it to `web3wallet.pair(uri: wc_uri)` like dealing with QR code?

**Comment by Luzzotica** [comment]
@devLoganHere Use the [WalletConnectModal](https://pub.dev/packages/walletconnect_modal_flutter) package if you want easy deep linking between dapp/wallet.

If you still want to implement it custom, then feel free to copy the code in the [WalletConnectModalFlutter](https://github.com/WalletConnect/WalletConnectModalFlutter) repo.
