### ISSUE TITLE
Signing a message to a custom network not working

### ISSUE THREAD

**Issue by samuel2629** [WalletConnect/WalletConnectFlutterV2#164]
When signing a message through Ethereum or Goerli it is working fine through : 

`
launchUrl(_uri, mode: LaunchMode.externalApplication);                                                     
await wcClient.request(topic: _sessionData!.topic, chainId: "eip155:$chainToConnect", request: SessionRequestParams(method: 'personal_sign', params: [message, EthereumAddress.fromHex(address.value).hex]));
`

But when it is a custom network like SKALE, with id "eip155:1517929550" it doesn't work, the pop-up of sign is not showing in metamask.

This is what i get back : 

`pairing sendResult, id: null topic: fa58510fd9f8ad6f89147ac3885231da19de18d1f325eedf1314cfdc6ae0a365, method: wc_sessionRequest, params: WcSessionRequestRequest(chainId: eip155:1517929550, request: SessionRequestParams(method: personal_sign, params: [0x535f0849b570b9dd9ea6cba61438fa7d90f8bf8b4e429e0d9a208bf58da6eca2, 0xb767bf40a58b6c20555973dd2cde3e5b5467b14e])), ttl: null`

**Comment by Luzzotica** [comment]
What wallet are you using?

Are you sure the wallet is on the SKALE network?

**Comment by samuel2629** [comment]
From the app, it opens Metamask, first i connect on the SKALE network, no issue on that part, next, when i try to sign through "personal_sign" no popup appears, when if i try on Goerli or Ethereum it is ok.
I added the SKALE network on Metamask as a custom network and on that side it is ok also.

**Comment by samuel2629** [comment]
I contact them and they don't have a "personal_sign" method on their network. 
This answer close the issue.

**Comment by samuel2629** [comment]
I contact them and they don't have a "personal_sign" method on their network. 
This answer close the issue.
