### ISSUE TITLE
WalletConnect Pairing Failure

### ISSUE THREAD

**Issue by nziokajimkelly** [WalletConnect/WalletConnectFlutterV2#165]
Trying to connect to connect to a app via using the example wallet Flutter app always fails with the following error message:

` pairing sendError, id: 1690910485700582 topic: b3909966c196afb1d9e2078c42ad87b1c560b0a9faecbe8bd79fcd72d3f5caba, method: wc_sessionPropose, error: JsonRpcError(code: 5101,
message: Unsupported methods. onSessionProposeRequest namespaces methods don't satisfy requiredNamespaces methods for eip155`

Steps To Reproduce

1. Clone the Flutter example app.
2. Cd into the example/wallet directory.
3. Run app
4. Go to site like https://www.metaforo.io. Click `Connect`. Copy the WalletConnect uri link
5. Paste copied link above into the text field expecting the aforementioned URI
6. Optionally, you can just scan the WalletConnect Qr code.
7. Notice the above error

**Comment by Luzzotica** [comment]
Hmmm, they are requesting a method I am not providing then. Gotta improve that error to give more details. Wonder which one it is...

**Comment by Luzzotica** [comment]
Please try again with v2.0.16 and post the error here

**Comment by Luzzotica** [comment]
Closing this as resolved.
