### ISSUE TITLE
Not able to use sendTransaction

### ISSUE THREAD

**Issue by espsofttech** [WalletConnect/WalletConnectFlutterV2#166]
Hello Team,
We are facing an issue after launching wallet connect v2.
We are not able to use sendTransaction method with contract integration in the Flutter mobile application.
We tried different libraries and packages to resolve this issue but still didn't get any proper solution to this. Kindly guide us to resolve this issue.
I have a question, Does the new Wallet connect V2 provide any provider?
If yes, Please help us out with this

![image](https://github.com/WalletConnect/WalletConnectFlutterV2/assets/18483844/bb46a401-66a5-471b-a77c-28282d98df26)

I have attached a part of the Code for Send Transaction here for your reference
Kindly let me know if there is something wrong with this code. 

As I simply want to use  send transaction method through Metamask.
Waiting for your quick response.

Thanks

**Comment by Luzzotica** [comment]
Have you reviewed the ETH transactions in the example dapp?

**Comment by Luzzotica** [comment]
[Here](https://github.com/WalletConnect/WalletConnectFlutterV2/blob/f6c90f15c0997038f5f43f4e69a74c1f5745c094/example/dapp/lib/utils/crypto/eip155.dart#L102) is the example I put together for send transaction.

It should have everything you need to build the image above.

**Comment by Luzzotica** [comment]
Closing this as complete.
