### ISSUE TITLE
RPCError: got code -32000 with msg "gas required exceeds allowance (0)

### ISSUE THREAD

**Issue by flutterdevcodiste** [WalletConnect/WalletConnectFlutterV2#169]
I'm encountering an error during a transaction, but I noticed that the issue is resolved once I convert the gas price from **Gwei to Wei**. It seems that there might be a discrepancy in the gas price conversion. I believe there needs to be a modification in the following section

https://github.com/WalletConnect/WalletConnectFlutterV2/blob/f6c90f15c0997038f5f43f4e69a74c1f5745c094/example/wallet/lib/dependencies/chains/evm_service.dart#L252

**Comment by Luzzotica** [comment]
Solved in master
