### ISSUE TITLE
Confused about the relationship between pairings and sessions

### ISSUE THREAD

**Issue by mik3mast3rs** [WalletConnect/WalletConnectFlutterV2#17]
Hello! After reading the documentation, I still have several questions:

1. Do I need to pair the dApp and the Wallet before requesting to start a session?
2. The WalletConnect documentation says that the pairing lasts 30 days, by default: https://docs.walletconnect.com/2.0/advanced/what-changed-from-v1.0#pairings--sessions But after I make a pair and check the PairingInfo, I can see that it lasts only for 3 minutes.
3. This paragraph is confusing: 
`**Pairings** have longer expiration than Sessions because they are meant to be re-used for session proposals and they **can request an infinite number of session proposals between Dapps and Wallets**`
I thought that the onSessionProposal method is called only one time, when you first pair a wallet and a dApp.

**Comment by Luzzotica** [comment]
1. If you use the SignClient, the lib will request a Pairing and a Session at the same time, so you don't have to worry about when you request the Session.
2. If the PairingInfo is only lasting 3 minutes, that's a bug on my part that I must resolve. I will look into it.
3. Why is the sentence confusing? Pairings are a foundational layer that are used to communicate between dApps and Wallets. Once you setup a pairing you can use it to communicate in any way you wish: Signing, Authenticating, Events, Messages, etc.
onSessionProposal is emitted every time a dApp requests a Session with a Paired wallet.

I'll see if I can put together some graphics for the documentation to make this a bit more clear.
