### ISSUE TITLE
Wallet connect active network not showing 

### ISSUE THREAD

**Issue by rashmisridar** [WalletConnect/WalletConnectFlutterV2#172]
Hi Team, 
Connected the wallet as per the reference  [https://github.com/WalletConnect/WalletConnectFlutterV2/issues/163](Refered link). 

After connection success . Not retuning the active network .  
Example:-
If I change the network from Ethernet to Polygon then in the response I get both the network name . Active one is not showing . 
Please let me know the solution for this. Thanks

**Comment by Luzzotica** [comment]
If you want an example of this, please take a look [here](https://github.com/WalletConnect/Web3ModalFlutter/blob/2981053456ecd3511ca2e3a7f0def7c75e22af62/lib/services/w3m_service/w3m_service.dart#L215)
