### ISSUE TITLE
How to check is WC link was already rejected? 

### ISSUE THREAD

**Issue by r-oman-G** [WalletConnect/WalletConnectFlutterV2#174]
How to understand is WC connect link is not actual anymore? 

For example: copy WC connect link, than reject a proposal and try to pair to the same link again. How i can catch some exception about the link is not valid anymore?

**Comment by Luzzotica** [comment]
Sometimes you can't.

You can wait for the proposal to be rejected, and respond to that.

But that only works if the wallet has correctly implemented rejection logic, which may not be the case.

My suggestion would be to always create a new URI to pair with.
