### ISSUE TITLE
Failed host lookup: 'relay.walletconnect.com'

### ISSUE THREAD

**Issue by psycik** [WalletConnect/WalletConnectFlutterV2#180]
**Describe the bug**
In debug mode:
SocketException: Failed host lookup: 'relay.walletconnect.com' (OS Error: No such host is known.
, errno = 11001)

Release mode works fine.

**To Reproduce**
Run dApp example code on Windows in Debug mode.

**Expected behavior**
For this not to fail.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: Latest

**Additional context**
Not working:
`_web3App = await Web3App.createInstance(
      relayUrl:  'wss://relay.walletconnect.com',
      projectId: "realprojectid",
      metadata: const PairingMetadata(
        name: 'test',
        description: 'testWalletConnect',
        url: '#',
        icons: ['https:/#/icon.png'],
      ),
    );`

Using the IP of relay.walletconnect.com seems to work but my wallet never connects from the provided QR code.
`_web3App = await Web3App.createInstance(
      relayUrl:  'wss://54.221.204.16'
      projectId: "realprojectid",
      metadata: const PairingMetadata(
        name: 'test',
        description: 'testWalletConnect',
        url: '#',
        icons: ['https:/#/icon.png'],
      ),
    );`

**Comment by psycik** [comment]
Seems to be this issue: [https://github.com/flutter/flutter/issues/129121](https://github.com/flutter/flutter/issues/129121)

Moving passed the exception everything works as expected.

**Comment by Luzzotica** [comment]
Ok, I am closing this issue then.

Thanks for finding that problem and the solution!
