### ISSUE TITLE
UNKNOWN METHOD Showing in Metamask Wallet Mobile App

### ISSUE THREAD

**Issue by TheQueenCho** [WalletConnect/WalletConnectFlutterV2#185]
While request **eth_sendTransaction** along my contract data to metamask wallet .
my contract method name not showing instead of its showing **UNKNOWN METHOD** 

 **flutter version :  3.10.6
  dart version : 3.0.6
iam using walletconnect_flutter_v2: ^2.1.4**

// reference image
![Screenshot_1693834525 (1)](https://github.com/WalletConnect/WalletConnectFlutterV2/assets/144307712/791f6e5d-c09a-4195-87c2-20983e5c9e54)

**Comment by Avinash-tech-bit** [comment]
facing same issue

**Comment by bobwith2bees** [comment]
Is the contract source published so that it shows up on https://mumbai.polygonscan.com/address with the function names intact?

I don't believe the name of the function actually goes into the transaction request submitted to the wallet.  

![image](https://github.com/WalletConnect/WalletConnectFlutterV2/assets/81196211/0a20e64b-3fe6-4c63-a9cb-6223bdc8a2d1)

**Comment by TheQueenCho** [comment]
> Is the contract source published so that it shows up on https://mumbai.polygonscan.com/address with the function names intact?
> 
> I don't believe the name of the function actually goes into the transaction request submitted to the wallet. https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_sendtransaction
> 
> ![image](https://user-images.githubusercontent.com/81196211/266380530-0a20e64b-3fe6-4c63-a9cb-6223bdc8a2d1.png)

Hey bob,
My contract method name showing on web extension  perfectly and also good at mumbai polygon contract ,
i am facing this issue only on mobile app ,even my contract hitting perfectly as expected

**Comment by Walter-White-atoms** [comment]
Hi there, any updates ? @TheQueenCho

**Comment by TheQueenCho** [comment]
Nope, Still stuck on same problem  @Walter-White-atoms
don't know why its not showing on mobile app

**Comment by bobwith2bees** [comment]
No insights here besides the common developer comment: "I don't have the problem on my box/" (code) with Android Metamask.  Have you also asked on the Metamask mobile issues? https://github.com/MetaMask/metamask-mobile/issues

Given your able to call the contract successfully, and the spec doesn't include the name of the function in the transaction request sent via walletconnect - I have little faith using my code will make a difference. 

That said - if it helps to have a working example my code is public:
 * https://gitlab.com/graflr/flutter_web3_demo
 * I call web3dart without creating the transaction manually.  See https://gitlab.com/graflr/flutter_web3_demo/-/wikis/web3dart-and-walletconnect_flutter_v2

 Curious what the WalletConnect folks have to say.

**Comment by TheQueenCho** [comment]
Ok bob i will try there , 
thanks for support
https://github.com/MetaMask/metamask-mobile/issues/7199

**Comment by Walter-White-atoms** [comment]
are you able to fixed this issue ? @TheQueenCho

**Comment by TheQueenCho** [comment]
Hey walter ,
- This is not walletConnect issue , This unknown method could be fixed by metamask side 
- Already there was an open issue related this ,check out link below
- So i am closing this as an invalid
https://github.com/MetaMask/metamask-mobile/issues/5929
Thanks for quick response guys

**Comment by IDontLikeOpen** [comment]
I had the same issue, and what helped me was including method data among other parameters.
You can get yours in the ABI of the token you are interacting with (in your case you go to https://etherscan.io/ and find your method's description) and insert it into you transaction parameters as data, so it will look like this: 
`yourTransferMethod()
      .send({
        from: senderAddress,
        gasPrice,
        data: {
    "constant": false,
    "inputs": [
      {
        "name": "to",
        "type": "address"
      },
      {
        "name": "value",
        "type": "uint256"
      }
    ],
    "name": "transfer",
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "payable": false,
    "stateMutability": "nonpayable",
    "type": "function"
  },
});`

Don't forget to add parameters in input! If you are not sure how to do it, try to test writing the contract on https://etherscan.io/ and extracting transaction data in hex from there, as shown in the image http://joxi.ru/xAepNGqCVWqdK2. To decode hex to the data you need use https://lab.miguelmota.com/ethereum-input-data-decoder/example/

 I hope it works for you 👍
