### ISSUE TITLE
Got an error when tried to respond the SessionRequestEvent: No matching key. proposal id doesn't exist

### ISSUE THREAD

**Issue by mmMrz** [WalletConnect/WalletConnectFlutterV2#187]
**Describe the bug**
`WalletConnectError(code: 2, message: No matching key. proposal id doesn't exist: 1694370881267306, data: null)`

**To Reproduce**
1. Go to Dapp: 'https://pancakeswap.finance/swap'
2. Login with the WalletConnectV2
3. Try to change chain on Pancake dapp
4. Will receive a SessionRequestEvent.
5. Try to respond this error like:
```
await _client.respondSessionRequest(
        topic: request.topic,
        response: JsonRpcResponse<String>(
          id: request.id,
          result: 'Signed!',
        ));
````
7. Got the error

**Expected behavior**
Successfully responding to this method, Pancake should switch chains correctly, just like TrustWallet or MetaMask did

**Smartphone (please complete the following information):**
 - Device: Pixel6
 - OS: Android 13
 - Version with the `walletconnect_flutter_v2: ^2.1.4`

**Additional context**
After receiving the SessionRequestEvent event, I called the getActiveSessions() and getPendingSessionRequests() methods before calling respondSessionRequest, and the ActiveSession is has correct value but the PendingSessionRequest is {}, an emtpy Map.

Thank you very much. Looking forward to your reply

**Comment by quetool** [comment]
Hello @mmMrz, sorry for the late response. Do you still need help? If so, can you provide a minimum reproducible code? Also, could you check if this helps? https://github.com/WalletConnect/WalletConnectFlutterV2/issues/94
