### ISSUE TITLE
[onSessionRequest doesn’t return anything]

### ISSUE THREAD

**Issue by Fabrice-Fabio** [WalletConnect/WalletConnectFlutterV2#189]
[onSessionRequest doesn’t return anything]

I'm trying to listen to the requests sent by the dapp when I need to sign or confirm a transaction, for example:

eth_sendTransaction
eth_sign
eth_signTransaction
eth_signTypedData
However, if I follow the documentation, I should have something like this:

wcClient.onSessionRequest.subscribe((SessionRequestEvent? args) {
}

And I should be able to retrieve the value of the method returned by the dapp.

This "wcClient.onSessionRequest.subscribe()" method called in my code doesn't trigger.

However, I've also noticed in the documentation that there is code like this:

wcClient.registerRequestHandler(
chainId: 'eip155:1',
method: 'eth_sendTransaction',
handler: signRequestHandler,
);

This one also doesn't trigger the "signRequestHandler()" function.

Any ideas?

After your responses, I'll try to update the documentation to make it more understandable for the community.

**Comment by Cagatay342** [comment]
It started after IOS17 on me

**Comment by quetool** [comment]
Hello @Fabrice-Fabio! Since we are discussing it here https://github.com/WalletConnect/WalletConnectFlutterV2/issues/192 I'll close this one. Thanks!
