### ISSUE TITLE
WC URI without methods param gives "_CastError (Null check operator used on a null value)"

### ISSUE THREAD

**Issue by dmdeklerk** [WalletConnect/WalletConnectFlutterV2#19]
Hi,

When the wallectconnect uri does not contain a 'methods' property in its queryParams, the below code throws.

```
class WalletConnectUtils {
  /// code removed ... 
  static URIParseResult parseUri(Uri uri) {
    /// code removed ... 
    List<String> methods = uri.queryParameters['methods']!
``` 

This occurs when trying out the linked WC V2 Dapp demo on the WC v2 docs page

- https://docs.walletconnect.com/2.0/javascript/guides/examples-and-resources
- https://react-app.walletconnect.com/

That said, I cant seem to find a writeup on the wc uri format for version 2 at the official doc site: https://docs.walletconnect.com/2.0, which leaves me in doubt if the methods param is required or not.

**Comment by Luzzotica** [comment]
Resolved by #24
