### ISSUE TITLE
WalletConnectError(code: 5, message: Missing or invalid. respondAuth() invalid id: 1695647682873183. No pending request found., data: null)

### ISSUE THREAD

**Issue by Fabrice-Fabio** [WalletConnect/WalletConnectFlutterV2#192]
WalletConnectError(code: 5, message: Missing or invalid. respondAuth() invalid id: 1695647682873183. No pending request found., data: null)

There’s two ways to catch onSessionRequest, for example :

1. First like mention on the documentation
wcClient.registerRequestHandler(
  chainId: 'eip155:$_currentNetworkId',
  method: 'eth_sendTransaction',
  handler: ethSendTransaction,
);

With this one, there’s one problem, when you decide to confirm the transaction, you won’t be able to send good “[args.id](http://args.id/)” like this because it is not available on registerRequestHandler params, it just got two params :

await wcClient.respondAuthRequest(
  id: args.id,
  iss: 'did:pkh:eip155:1:ETH_ADDRESS',
  signature: CacaoSignature(t: CacaoSignature.EIP191, s: sig),
);

2. Use wcClient.onSessionRequest.subscribe

With this one, everything look like it can work, but one thing is weird when you confirm the transaction from dapp like pancakeswap, paraswap… :

await wcClient.respondAuthRequest(
  id: requestId,
  iss: 'did:pkh:eip155:${_currentNetworkId}:${_currentAddress}',
  signature: CacaoSignature(t: CacaoSignature.EIP191, s: txhash),
);

There’s an error come from walletconnect_flutter_v2, and even if transaction has been made and confirm on bsscan or polygonscan, dapp and wallet will trought you an error :
“WalletConnectError(code: 5, message: Missing or invalid. respondAuth() invalid id: 1695647682873183. No pending request found., data: null)”

After I check source code, I’ve noticed a function called “authEngine.respondAuthRequest()” in auth_engine.dart file, and this one is making a verification at :
- Map<int, PendingAuthRequest> pendingRequests = getPendingAuthRequests();
But the problem is getPendingAuthRequests() are trying to check if requestId exist in authRequests.getAll() function which are always return {}

So please guy, I think there’s a big issue which always return WalletConnectError(code: 5, message: Missing or invalid. respondAuth() invalid id: 1695647682873183. No pending request found., data: null). 

@Luzzotica @SametSahin10 @iota9star

**Comment by quetool** [comment]
Hello @Fabrice-Fabio! Thanks for reaching out and apologies for the delayed response! We are going to look at your report ASAP and will get back to you!
Thanks for your patience! 🙏

**Comment by quetool** [comment]
Hello @Fabrice-Fabio, first of all I apologize for the delayed response!
Based on your comment looks like you are trying to approve an already approved Auth request but in reality what you want to do is to sign/send a transaction, is that correct? 

If what you are trying to achieve is to to sign/send a Transaction then your handler should look somehow like this one in the example app: https://github.com/WalletConnect/WalletConnectFlutterV2/blob/bdda5e9a8834dd11f535c06789c3f2b46d601e9b/example/wallet/lib/dependencies/chains/evm_service.dart#L219

If you instead want to subscribe to `onSessionRequest` then the handler should be basically the same but you should use `args.params` to construct the Transaction.

This is `SessionRequestEvent` object:

```
class SessionRequestEvent extends EventArgs {
  int id;
  String topic;
  String method;
  String chainId;
  dynamic params;

  SessionRequestEvent(
    this.id,
    this.topic,
    this.method,
    this.chainId,
    this.params,
  );

  factory SessionRequestEvent.fromSessionRequest(
    SessionRequest request,
  ) {
    return SessionRequestEvent(
      request.id,
      request.topic,
      request.method,
      request.chainId,
      request.params,
    );
  }

  @override
  String toString() {
    return 'SessionRequestEvent(id: $id, topic: $topic, method: $method, chainId: $chainId, params: $params)';
  }
}
```

`respondAuthRequest` should be used only for dapp/wallet authentication requests, you can see a full implementation here https://github.com/WalletConnect/WalletConnectFlutterV2/blob/bdda5e9a8834dd11f535c06789c3f2b46d601e9b/example/wallet/lib/dependencies/web3wallet_service.dart#L172

I hope this helps, let me know! Thanks!
