### ISSUE TITLE
Request signatures

### ISSUE THREAD

**Issue by AdnanIcetulip** [WalletConnect/WalletConnectFlutterV2#200]
How can i get the transaction hash after i got the signResponse
 final dynamic signResponse = await wcClient.request(
  topic: session.topic,
  chainId: 'eip155:1',
  request: SessionRequestParams(
    method: 'eth_sendTransaction',
    params: 'json serializable parameters',
  ),
);

**Comment by quetool** [comment]
Hello @AdnanIcetulip , isn't the signResponse what you are looking for?

**Comment by quetool** [comment]
Fee free to reopen If needed!
