### ISSUE TITLE
Request to have a feature similar to WalletConnectRouter on iOS SDK to allow navigating back to the dApp after approval or rejection.

### ISSUE THREAD

**Issue by CyberWake** [WalletConnect/WalletConnectFlutterV2#202]
**Is your feature request related to a problem? Please describe.**
Yes, On iOS device after signing a connection/transaction request from other app from other application. I am not able to redirect to it.

**Describe the solution you'd like**
I am not aware of it as of now.

**Describe alternatives you've considered**
I have tried the one like asking the connecting dapp the deep link to it in with my applications deep link with the connection uri. Which would yet only work for that application only.

**Additional context**
On iOS wallet connect sdk there is a option to navigate back to the requesting dApp. With the use of WalletConnectRouter marked [here](https://docs.walletconnect.com/web3wallet/mobileLinking) in the docs and [here](https://github.com/WalletConnect/WalletConnectSwiftV2/blob/c4adea7da8f341373f2bdb2d2271b85e89191fb3/Sources/WalletConnectRouter/Router.m) in the iOS SDK repo.

**Comment by bobwith2bees** [comment]
A DApp can provide it's registered native or universal links, much like a wallet can provide in the WalletConnect Registry.  App redirects are provided to the wallet in the peer metadata for the signing session.  The wallet can then launch the appropriate link to return to the specific app (assuming both apps are on the same device.)

Flutter examples how to call the redirects can be seen here: https://github.com/WalletConnect/WalletConnectModalFlutter/blob/master/lib/services/utils/url/url_utils.dart

Are you asking for the Flutter plugin (DAPP) to work with the IOS SDK referenced?  This might not be the repo to ask, I'll let the team decide.

**Comment by quetool** [comment]
Hello @CyberWake, as @bobwith2bees correctly says, you can define your `redirect:` object in the Web3App `PairingMetadata` parameter.

For instance:
```
final Web3App web3App = await Web3App.createInstance(
  projectId: 'YOUR_PROJECT_ID',
  metadata: const PairingMetadata(
    name: 'Flutter Dapp Example',
    description: 'Flutter Dapp Example',
    url: 'https://www.walletconnect.com/',
    icons: ['https://walletconnect.com/walletconnect-logo.png'],
    redirect: Redirect(
      native: 'flutterdapp://',
      universal: 'https://www.walletconnect.com',
    ),
  ),
);
```

**Comment by quetool** [comment]
Hello @CyberWake, can this be closed?

**Comment by AnhTu6610** [comment]
> Hello @CyberWake, as @bobwith2bees correctly says, you can define your `redirect:` object in the Web3App `PairingMetadata` parameter.
> 
> For instance:
> 
> ```
> final Web3App web3App = await Web3App.createInstance(
>   projectId: 'YOUR_PROJECT_ID',
>   metadata: const PairingMetadata(
>     name: 'Flutter Dapp Example',
>     description: 'Flutter Dapp Example',
>     url: 'https://www.walletconnect.com/',
>     icons: ['https://walletconnect.com/walletconnect-logo.png'],
>     redirect: Redirect(
>       native: 'flutterdapp://',
>       universal: 'https://www.walletconnect.com',
>     ),
>   ),
> );
> ```

I tried it and it doesn't work

**Comment by quetool** [comment]
Are you also adding your custom scheme on iOS Info.plist file under `CFBundleURLTypes` key?

```
<key>CFBundleURLTypes</key>
<array>
	<dict>
		<key>CFBundleURLName</key>
		<string>com.web3modal.flutterExample</string>
		<key>CFBundleURLSchemes</key>
		<array>
			<string> flutterdapp </string>
		</array>
	</dict>
</array>
```

Bear in mind that there is currently an issue on iOS 17 in regards of deep linking https://docs.walletconnect.com/web3wallet/mobileLinking

**Comment by AnhTu6610** [comment]
> Are you also adding your custom scheme on iOS Info.plist file under `CFBundleURLTypes` key?
> 
> ```
> <key>CFBundleURLTypes</key>
> <array>
> 	<dict>
> 		<key>CFBundleURLName</key>
> 		<string>com.web3modal.flutterExample</string>
> 		<key>CFBundleURLSchemes</key>
> 		<array>
> 			<string> flutterdapp </string>
> 		</array>
> 	</dict>
> </array>
> ```
> 
> Bear in mind that there is currently an issue on iOS 17 in regards of deep linking https://docs.walletconnect.com/web3wallet/mobileLinking

it still doesn't work.

**Comment by quetool** [comment]
iOS Info.plist

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	...
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>myflutterdapp</string>
			</array>
		</dict>
	</array>
	...
</dict>
</plist>
```

AndroidManifest.xml
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
   <application
        android:label="dapp"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="myflutterdapp" />
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
```

Dapp definition on Flutter:

```dart
final web3App = await Web3App.createInstance(
  projectId: DartDefines.projectId,
  logLevel: LogLevel.info,
  metadata: const PairingMetadata(
    name: 'Example dApp',
    description: 'Example dApp',
    url: 'https://yourwebsite.com',
    redirect: Redirect(
      native: 'myflutterdapp://',
      universal: 'https://youruniversal.link',
    ),
  ),
);
```

This should be enough to allow the wallet redirect back to your dapp. If that doesn't occur is either because the wallet didn't implement it or you are running on iOS 17.

Feel free to reopen if needed!
