### ISSUE TITLE
WalletConnect sdk is ignoring optional namespace's methods when connecting to dApp

### ISSUE THREAD

**Issue by Volfor** [WalletConnect/WalletConnectFlutterV2#205]
WalletConnect is ignoring optional namespace's methods (and probably events) when connecting to dApp. 

**WalletConnect version**: ^2.1.5

For example: 
I'm connecting to Uniswap, it has the following required namespaces:
```
requiredNamespaces: {
  eip155: RequiredNamespace(
    chains: [eip155:11155111], 
    methods: [eth_sendTransaction, personal_sign], 
    events: [chainChanged, accountsChanged]
  )
}
```
and optional namespaces:
```
optionalNamespaces: {
  eip155: RequiredNamespace(
    chains: [eip155:1, eip155:5, eip155:11155111, eip155:137, eip155:80001, eip155:42220, eip155:44787, eip155:56, eip155:43114, eip155:42161, eip155:421613, eip155:10, eip155:420, eip155:8453], 
    methods: [eth_sendTransaction, personal_sign, eth_signTypedData, eth_signTypedData_v4, eth_sign], 
    events: [chainChanged, accountsChanged, message, disconnect, connect]
  )
}, 
```

But if you take a look at generated namespaces by Wallet Connect, they look like this:
```
generatedNamespaces: {
  eip155: Namespace(
    accounts: [eip155:11155111:0x6414F8201d5406D2ebC438eADf0FE0CBd532F805], 
    methods: [personal_sign, eth_sendTransaction], 
    events: [chainChanged, accountsChanged]
  )
}
```
Please note that our wallet has registered handlers for all requested methods (both required and optional), and as you can see, generated namespaces only has two methods.

My guess is that this `_constructNamespacesFromRequired` function should unite methods and events instead of intersecting them.

For example in my case with Uniswap, if you take a look at this line  https://github.com/WalletConnect/WalletConnectFlutterV2/blob/d299d9b764acab6c6a2670eef47c7cb040cde2de/lib/apis/utils/namespace_utils.dart#L355

the first set in the list is empty, so intersecting it with any other set will return empty set. Because of this, generated namespaces only has methods from the required namespaces. Same for events (next line).

I hope my explanation is clear, if not, please ask me for any details. 

Thank you.

**Comment by quetool** [comment]
Thank you for the report, @Volfor, and sorry for the late response! I'll try to take a look a this in the following days!

**Comment by quetool** [comment]
Hello @Volfor, sorry for the late response. I tried this and worked fine for me with Uniswap. I've basically ran the example dApp from the repo with your suggested required and optional namespaces. Do you mind trying in latest version 2.1.8? And if you still encounter the issue, do you mind trying by sending everything as optionalNamespace? Thanks!

**Comment by Volfor** [comment]
Thanks @quetool, I'll give it a try and get back to you as soon as I can

**Comment by Volfor** [comment]
@quetool , thanks for waiting

> I've basically ran the example dApp from the repo with your suggested required and optional namespaces.

Required and optional namespaces I provided is what Uniswap expects. 

The problem is that namespaces generated by walletConnect flutter SDK don't include optional methods, only required ones (the same with events, but I omitted them for simplicity). 
By generated namespaces I mean namespaces created with `NamespaceUtils.constructNamespaces` which happens on _onSessionProposeRequest: 
https://github.com/WalletConnect/WalletConnectFlutterV2/blob/f84c5ada9e72e76cb1dc40119fdb9f80d765c9b2/lib/apis/sign_api/sign_engine.dart#L910


So for example if dApp expects the following namespaces:

```
requiredNamespaces: {
  eip155: RequiredNamespace(
    chains: [eip155:11155111], 
    methods: [eth_sendTransaction, personal_sign], 
    events: [chainChanged, accountsChanged]
  )
}
```
```
optionalNamespaces: {
  eip155: RequiredNamespace(
    chains: [eip155:1, eip155:5, eip155:11155111, eip155:137, eip155:80001, eip155:42220, eip155:44787, eip155:56, eip155:43114, eip155:42161, eip155:421613, eip155:10, eip155:420, eip155:8453], 
    methods: [eth_sendTransaction, personal_sign, eth_signTypedData, eth_signTypedData_v4, eth_sign], 
    events: [chainChanged, accountsChanged, message, disconnect, connect]
  )
}, 
```

and my wallet supports only `eip155:11155111` chain and has registered handlers (with `web3Wallet.registerRequestHandler`) for all these methods: eth_sendTransaction, personal_sign, eth_signTypedData, eth_signTypedData_v4, eth_sign,

shouldn't the result of `NamespaceUtils.constructNamespaces` be something like this?
```
generatedNamespaces: {
  eip155: Namespace(
    accounts: [eip155:11155111:0x6414F8201d5406D2ebC438eADf0FE0CBd532F805], 
    methods: [eth_sendTransaction, personal_sign, eth_signTypedData, eth_signTypedData_v4, eth_sign], 
    events: [chainChanged, accountsChanged]
  )
}
```

---

> do you mind trying by sending everything as optionalNamespace?

`web3Wallet.approveSession` only has namespaces parameter, this is the current logic I have:
```
final response = await web3Wallet.approveSession(
  id: args.id,
  namespaces: args.params.generatedNamespaces ?? {},
);
```
I imagine that the wallet can only send namespaces that it supports, so I'm not sure what you meant by that.

**Comment by Volfor** [comment]
@quetool 

Maybe it's related to this? [CAIP-25 Implementation Guidance: Migrating to Empty / Undefined Required Namespaces](https://medium.com/walletconnect/caip-25-implementation-guidance-migrating-to-empty-undefined-required-namespaces-6aa5626a86d9)

Are there any plans to add/update this [namespace builder util tool](https://docs.walletconnect.com/web3wallet/namespaces#updating-your-wallets-namespaces-implementation) for Flutter?

**Comment by quetool** [comment]
Hello @Volfor, I'll forward this to our DevRel team for further investigation but, what I'm suggesting (and doing myself) is indeed [Case No. 1 ](https://docs.walletconnect.com/web3wallet/namespaces#case-no-1---recommended-default-for-all-apps)

Maybe Uniswap is expecting something different. I hope I can get back to you soon with further info.

**Comment by Volfor** [comment]
> @Volfor can you remind me what's your use case?
> 
> 1. You are developing a wallet and trying to connect Uniswap dApp with it o
> 2. You are developing a dapp and trying to connect to Uniswap wallet?
> 
> Thanks

@quetool 1st one

Connection itself works fine. Problems comes when I'm trying to swap UNI to ETH and dApp wants to sign a message using `eth_signTypedData_v4` method. Signing fails because this method was missing in the generated namespaces I sent in `web3Wallet.approveSession()` (even though my wallet app has registered handler for it)

**Comment by quetool** [comment]
Gotcha! I was able to reproduce the issue and all points that you are right, I will be confirming the proper functionality and hopefully have a fix by the end of the week. Sorry for the inconvenience!

**Comment by quetool** [comment]
Hello @Volfor, can you please confirm you are registering not just eventEmitters and methodHandlers but also accounts? Check this answer here https://github.com/WalletConnect/WalletConnectFlutterV2/issues/230#issuecomment-1845368534

**Comment by quetool** [comment]
GM @Volfor! Version 2.1.11 has been pushed. Do you mind checking if your issue has been fixed? Thanks!

**Comment by quetool** [comment]
Thanks to you for the report! 🙌
