### ISSUE TITLE
How to use VerifyAPI on WalletConnectFlutter

### ISSUE THREAD

**Issue by devLoganHere** [WalletConnect/WalletConnectFlutterV2#207]
There's VerifyAPI usage for Android and iOS.
https://docs.walletconnect.com/web3wallet/verify

But I couldn't find the usage for Flutter.
I'm using `walletconnect_flutter_v2: 2.1.4` flutter packages for our Wallet.
Please let me know the usage.

**Comment by quetool** [comment]
Hello @devLoganHere! Thanks for reaching out! Indeed VerifyAPI is not yet implemented in flutter sdks! We are aiming to do so ASAP!

**Comment by hayderux** [comment]
How we can use this API ? Can you please show an example here ? @quetool

**Comment by devLoganHere** [comment]
@quetool Thanks for checking it out.
Could you share the plan for VerifyAPI?

**Comment by quetool** [comment]
We are working on it as we speak. Not sure how it would take tho. Hopefully by the end of the week. I'll update this issue when done!

**Comment by devLoganHere** [comment]
Thank you so much! I'll give you feedback if it's updated so I can use it.

**Comment by quetool** [comment]
Hello @devLoganHere @hayderux 
Verify API is now supported on Flutter since 2.1.9 https://pub.dev/packages/walletconnect_flutter_v2/changelog

Implementation is as easies as this https://docs.walletconnect.com/web3wallet/verify#implementation
