### ISSUE TITLE
[BUG] WcSessionProposeRequest.optionalNamespaces should be optional!

### ISSUE THREAD

**Issue by dmdeklerk** [WalletConnect/WalletConnectFlutterV2#21]
The auto generated JsonSerializable code for WcSessionProposeRequest requires 'optionalNamespaces' to be a map, while the protocol could just omit this property. 
This leads to the below generated code to fail on session proposal responses without said property

```
WcSessionProposeRequest _$WcSessionProposeRequestFromJson(
        Map<String, dynamic> json) =>
    WcSessionProposeRequest(
    /// code removed ...
      optionalNamespaces:
          (json['optionalNamespaces'] as Map<String, dynamic>).map(
        (k, e) =>
            MapEntry(k, RequiredNamespace.fromJson(e as Map<String, dynamic>)),
      ),    
```

Exception thrown _CastError (type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast)

**Comment by Luzzotica** [comment]
The issue here is that I cannot omit it.

The javascript mono-repo `optionalNamespace` property is not optional. See [here](https://github.com/WalletConnect/walletconnect-monorepo/blob/218ffc2681d97f4aa02e0839a81a627c46d7dadf/packages/types/src/sign-client/jsonrpc.ts#L29)
So by omitting it, it would break the ability to communicate with the javascript monorepo (If the dApp or Wallet is using it).

**Comment by dmdeklerk** [comment]
Ok fair enough. 

In that case the dapp live demo has to be re-deployed to (probably) include this fix https://github.com/WalletConnect/web-examples/pull/112

[React dApp (with standalone client) - v2](https://github.com/WalletConnect/web-examples/tree/main/dapps/react-dapp-v2) ([Demo](https://react-app.walletconnect.com/))

**Comment by Luzzotica** [comment]
It looks like the dApp at least checks for non-null optionalNamespace before doing anything with it, so there that.

Perhaps I can add it without worrying then. 

I'm not too familiar with TS, I just assume that if the type doesn't set it as optional, then it must exist.

**Comment by dmdeklerk** [comment]
Looking at the place the monorepo [sends this request](https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/packages/sign-client/src/controllers/engine.ts#L153) to the WC client.
It does seem that a [few lines up](https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/packages/sign-client/src/controllers/engine.ts#L91) the code ensures `optionalNamespace` is a property.

That said, it is considered 'normal' practice in lots of environments to omit empty list and object properties instead of including them with an empty object or list json literal.

**Comment by Luzzotica** [comment]
I agree with you. 
We just didn't want to break our protocol I believe. 
I remember seeing some reasoning about this. 
Let me follow up with the team.

I think the end goal is to move to optional values, as that would just be much nicer in the long run, and as you say "normal" or standard.
Until then, we will keep it.
I can likely abstract it away from you the end user though, and just ensure it exists when sending it across the pipe. I'll look into it.

**Comment by dmdeklerk** [comment]
From the spec: https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-25.md

> **if present**; the optionalNamespaces array MUST contain 1 or more of them, if present.

So this means requiring optionalNamespace to be present breaks the specification.
