### ISSUE TITLE
Help for issues that cannot be connected

### ISSUE THREAD

**Issue by gztcode** [WalletConnect/WalletConnectFlutterV2#213]
**Describe the bug**
Since October 28th, our project ID has been `b8ff2c34d151d8c8c58f882026e8021a`. The application name is Ape Wallet, and the WC function of our application has entered a paralyzed state. Other project ID `95db360551ea3df8634efdc4d7324a0b` connections and transaction initiation are normal.

After scanning **_onPairingCreate** will have a callback. But **_onSessionProposal or _onPairingDelete or _onPairingInvalid** does not receive a callback

**Expected behavior**
I just want to know why this situation exists? And how to solve this problem 

**Smartphone (please complete the following information):**
 - Device: [iPhonexs]
 - OS: [iOS16.6.1.1]
 - Version [2.1.4~2.1.8]

**Additional context**

``` dart
 String appName = (await PackageInfo.fromPlatform()).appName;
    _web3Wallet = Web3Wallet(
      core: Core(
        projectId: AConstant.wc_id,
      ),
      metadata: PairingMetadata(
        name: appName,
        description: "${appName}:${AConstant.wc_description}",
        url: AConstant.wc_url,
        icons: AConstant.wc_icons,
      ),
    );
    WalletConnectV2Config.initData(_web3Wallet, this.publicKey);
    _web3Wallet.core.pairing.onPairingInvalid.subscribe(_onPairingInvalid);
    _web3Wallet.core.pairing.onPairingCreate.subscribe(_onPairingCreate);
    _web3Wallet.core.pairing.onPairingDelete.subscribe(_onPairingDelete);
    _web3Wallet.core.pairing.onPairingExpire.subscribe(_onPairingDelete);
    _web3Wallet.pairings.onSync.subscribe(_onPairingsSync);
    _web3Wallet.onSessionProposal.subscribe(_onSessionProposal);
    _web3Wallet.onSessionProposalError.subscribe(_onSessionProposalError);
    _web3Wallet.onSessionConnect.subscribe(_onSessionConnect);
    _web3Wallet.onSessionDelete.subscribe(_onSessionDelete);
    _web3Wallet.onSessionExpire.subscribe(_onSessionExpire);

    _web3Wallet.onSessionRequest.subscribe(_onSessionRequest);
    
```

**Comment by quetool** [comment]
Hello @gztcode, looking into this right now. Any particular difference between `b8ff2c34d151d8c8c58f882026e8021a` and `95db360551ea3df8634efdc4d7324a0b`?

**Comment by 0x0077** [comment]
> Hello @gztcode, do you mind checking if you have set allowed domains in your cloud configuration and, if so, removing it and trying again? It might take up to 2 hours for the cache to expire once you remove the allowed origins from your Cloud Dashboard so it might not work instantly

Glad to hear back from you. We'll promptly try removing the authenticated domain and then reconfigure it. 
Additionally, `b8ff2c34d151d8c8c58f882026e8021a` is our official project ID, while `95db360551ea3df8634efdc4d7324a0b` is the ID we're using for testing.

**Comment by 0x0077** [comment]
@quetool I've come back again. I've already reset the domain name and re-verified it, but it's still not working. What else can I do?

**Comment by quetool** [comment]
In your cloud configuration, http://cloud.walletconnect.com, do you have set a specific allowed origin? If yes then remove it, leave it blank, and wait a couple of hours. Allowed origins from mobile is not supported.

**Comment by 0x0077** [comment]
okay. Try it again

**Comment by 0x0077** [comment]
@quetool It's working now, thank you for your answer

**Comment by quetool** [comment]
Thanks!
