### ISSUE TITLE
Auth request not working 

### ISSUE THREAD

**Issue by oyen-bright** [WalletConnect/WalletConnectFlutterV2#214]
```
final AuthRequestResponse authReq =
    await WalletConnectConfig.wcAuthClint.request(
  params: AuthRequestParams(
    aud: 'http://localhost:3000/login',
    domain: 'localhost:3000',
    chainId: 'eip155:1',
    statement: 'Sign in with your wallet!',
  ),
);
await WalletConnectConfig.onDisplayUri(authReq.uri, WalletType.metamask);
```

it opens Metamask but noting happens

**Comment by oyen-bright** [comment]
@quetool

**Comment by quetool** [comment]
Hello @oyen-bright!
Can you try a different wallet? Like Rainbow? it usually gives you a bit of more context

**Comment by quetool** [comment]
Also, do you mind checking this issue? https://github.com/WalletConnect/WalletConnectFlutterV2/issues/206

**Comment by quetool** [comment]
Also, for reference, this is how connect should work https://github.com/WalletConnect/WalletConnectFlutterV2/blob/master/example/dapp/lib/pages/connect_page.dart#L163

**Comment by quetool** [comment]
Check also this very simply gist https://gist.github.com/quetool/f934b449ed0027f8b435622a2719328a

**Comment by oyen-bright** [comment]
Hello, I have successfully connected with Metamask following the steps
outlined in this gist and established a session. I now aim to implement the
authrequest feature, allowing users to log in with their wallets. Could you
please provide a detailed Git flow for this process? Your guidance is
highly appreciated. Thank you!

**Comment by quetool** [comment]
Everything you need to know is here in the example app I've sent before. After establishing the connection you can then request auth https://github.com/WalletConnect/WalletConnectFlutterV2/blob/master/example/dapp/lib/pages/connect_page.dart#L202

Please try different wallet apps, such as trust and rainbow as MM sometimes does not give any feedback.

**Comment by quetool** [comment]
Also it is possible that MetaMask does not support Auth. I'm sure Rainbow and Trust (and probably other ones) does.

**Comment by oyen-bright** [comment]
Okay 

@quetool iI'm encountering an issue with sessions. Even after I terminate a session—something I do when users want to disconnect their wallets—upon app restart, the active session persists. I'm using the session to maintain the wallet connection. Could you please provide me with some insights into how sessions operate? I would appreciate any guidance or clarification on this matter.

  static void _restoreSession() {
    try {
      final activeSession = wcClient?.getActiveSessions();
      debugPrint(activeSession.toString());
      if (activeSession != null && activeSession.isNotEmpty) {
        session = activeSession.values.first;
        debugPrint("session restored");
      }
    } catch (e) {
      return;
    }
  }

  static Future<(String? error, bool isKilled)> killSession(
      SessionData sessionData) async {
    try {
      await wcClient?.disconnectSession(
          topic: sessionData.topic,
          reason: Errors.getSdkError(Errors.USER_DISCONNECTED));

      debugPrint("session killed");
      return (null, true);
    } catch (err, stackTrace) {
      debugPrint("Error $err $stackTrace");

      rethrow;
    }
  }

  static Future init() async {
    try {
      wcClient = await Web3App.createInstance(
        relayUrl: 'wss://relay.walletconnect.com',
        projectId: projectId,
        metadata: const PairingMetadata(
          name: '',
          description: '',
          url: 'https://walletconnect.com',
          icons: ['https://avatars.githubusercontent.com/u/37784886'],
        ),
      );

      debugPrint("web3App createInstance");
      _restoreSession();
    } catch (err, stackTrace) {
      debugPrint("web3App createInstance error $stackTrace");
    }
  }
