### ISSUE TITLE
web3Wallet.disconnectSession doesn't work in certain specific dapps

### ISSUE THREAD

**Issue by SwVc** [WalletConnect/WalletConnectFlutterV2#217]
Bug Description
When I click a button in my own app to call _web3Wallet!.disconnectSession, it displays a "Bad state: Future already completed" error.

Affected Dapps
The issue occurs in the "Summer.Fi Dapp," but it does not happen when using "OpenSea" and "React App."
React App : https://react-app.walletconnect.com/
Summer.fi: https://summer.fi/

Steps to Reproduce
Open the app.
Click the button to call _web3Wallet!.disconnectSession.
Observe the "Bad state: Future already completed" error in the "Summer.Fi Dapp."

WalletConnect version: ^2.1.5
Flutter version: 3.7.11
Dart : 2.19.6
Device: iPhone 12
OS: iOS 16.5

**Comment by quetool** [comment]
Hello @SwVc , if I get this right you are developing a **WALLET** with **walletconnect_flutter_v2 2.1.5** and you are connecting this wallet to **Summer.FI Dapp**. Then, when you disconnect your Wallet, you see this error log in your console or in the Summer.FI console?

Would be also nice a min reproducible code.
Thanks!

**Comment by SwVc** [comment]
Yes, I have a button in my app to disconnect the wallet, and I encounter issues when using that button.

**Comment by SwVc** [comment]
Hello, Is there any solution available for this issue?

**Comment by quetool** [comment]
Hello @SwVc, I asked for a minimum reproducible code before. However, I don't think this error log would affect the functionality of your Wallet, is it?

**Comment by quetool** [comment]
Can you install latest version (2.1.9) run the example wallet project and check if also there you see this error?

**Comment by SwVc** [comment]
Hello @quetool ,I tried connecting to a Dapp using the example wallet, and it worked successfully. However, when attempting to disconnect from the Dapp in the app, I was unable to successfully terminate the connection.

The code for disconnecting from the DApp in the example wallet is as follows:  
```
await GetIt.I<IWeb3WalletService>()
                            .getWeb3Wallet()
                            .core
                            .pairing
                            .disconnect(topic: widget.pairing.topic);
```

Here is my sample code:
```
 TagButton(
                  widget: Container(
                      margin: const EdgeInsets.symmetric(horizontal: 14, vertical: 6),
                      child: Row(
                        children: [
                          Text(
                            'disconnect'.tr,
                            style: const TextStyle(fontSize: 13, fontWeight: FontWeight.w700, color: AppColor.orange),
                          )
                        ],
                      )),
                  fontSize: 16,
                  borderRadius: 43,
                  backgroundColor: context.theme.primaryColor,
                  function: (c) async{                    
                    await _web3WalletService.getWeb3Wallet()!.disconnectSession(topic: model.topic, reason: Errors.getSdkError(Errors.USER_DISCONNECTED));
                  },
                ),
```

**Comment by SwVc** [comment]
When running in debug mode, my breakpoint stops at the class _AsyncCompleter<T> within the complete method:

![截圖 2023-11-20 下午3 35 45](https://github.com/WalletConnect/WalletConnectFlutterV2/assets/122099890/eeae6923-4e75-4f97-af44-28bc039fcd7c)

Then, I would like to inquire about the difference between .core.pairing.disconnect(topic: widget.pairing.topic) and _web3Wallet!.disconnectSession(). The reason being, in the Readme, _web3Wallet!.disconnectSession() is used. What distinguishes these two methods?

**Comment by quetool** [comment]
Hello @SwVc! Could you try latest 2.1.13 and reopen if needed? Thanks

**Comment by SwVc** [comment]
Hello @quetool ! The issues have been fixed, and it now works successfully. Thank you!
