### ISSUE TITLE
Request for Guidance: Interacting with Smart Contracts using WalletConnect in Flutter

### ISSUE THREAD

**Issue by oyen-bright** [WalletConnect/WalletConnectFlutterV2#219]
I am exploring the integration of WalletConnect in Flutter to interact with smart contracts and update their values. While attempting to implement this functionality, I encountered some challenges and sought further guidance on the best practices and recommended approaches for achieving this.

Specifically, I would appreciate more detailed documentation or examples demonstrating the seamless integration of WalletConnect with Flutter, especially focusing on the interaction with smart contracts and the process of updating their values.

Could the repository maintainers kindly provide insights, best practices, or any relevant examples that could facilitate the integration of WalletConnect for interacting with smart contracts in a Flutter environment?

**Comment by oyen-bright** [comment]
@quetool  can you please help me here ?

**Comment by bobwith2bees** [comment]
@oyen-bright  Feel free to play with https://gitlab.com/graflr/flutter_web3_demo and see how it deploys and makes simple contract calls. 

https://gitlab.com/graflr/flutter_web3_demo/-/blob/main/lib/logic/token_contract.dart?ref_type=heads

**Comment by quetool** [comment]
Hello! Check this out! https://github.com/WalletConnect/WalletConnectFlutterV2/issues/255
