### ISSUE TITLE
Request for documentation

### ISSUE THREAD

**Issue by Fabrice-Fabio** [WalletConnect/WalletConnectFlutterV2#220]
We notice in the code, the integration of verify Api but there's not example of code in readme of how to use it.
Same for the connection request widget.
Thanks

**Comment by quetool** [comment]
Hello @Fabrice-Fabio! Regarding the verify implementation you actually don't have to do nothing big, you can access the verifyContex (aka the result of the verification process) in the SessionProposalEvent. https://docs.walletconnect.com/web3wallet/verify?platform=flutter#implementation

```
_web3Wallet!.onSessionProposal.subscribe((SessionProposalEvent? args) {
  if (args != null) {
    final scamApp = args.verifyContext?.validation.scam;
    final invalidApp = args.verifyContext?.validation.invalid;
    final validApp = args.verifyContext?.validation.valid;
    final unknown = args.verifyContext?.validation.unknown;
  }
});
```

I'll update the example ASAP.

Regarding the "connection request widget", what do you mean exactly?

**Comment by Fabrice-Fabio** [comment]
Thanks Alfreedom,

I've update the readme by creating a pull request, please check it there and merge it if it suit you : https://github.com/WalletConnect/WalletConnectFlutterV2/pull/227/commits

Thanks.
