### ISSUE TITLE
Is there way to get changed chain event from DApp?

### ISSUE THREAD

**Issue by JanghoChu** [WalletConnect/WalletConnectFlutterV2#224]
I want to get changed chain event from DApp. 

I used Web3Wallet and added subscribes but i didn't get any changed chain event from DApp.

Please let me know how to get changed chain event.

I want  When I change chain in OpenSea,  My wallet app is changed chain too.

DApp: http://testnets.opensea.io/

**Comment by JanghoChu** [comment]
Thank you @quetool 

I only used Web3Wallet to connect with OpenSea(personal_sign, eth_sign, eth_sendTransaction, ... )

If I want to get changedChain event, Do I use web3App too?

**Comment by quetool** [comment]
Hello @JanghoChu! Please follow this thread as it is the most updated one! Thanks! 🙏 https://github.com/WalletConnect/WalletConnectFlutterV2/issues/235
