### ISSUE TITLE
The Verify API did not work

### ISSUE THREAD

**Issue by damaxi1010** [WalletConnect/WalletConnectFlutterV2#232]
After updating the plugin to version 2.1.10 and using the Verify API feature, when attempting to connect to the dapp by scanning the QR code, an error occurred in the _fetchAttestation method inside the Verify class, indicating [SignEngine] _getVerifyContext() error: Exception: Attestation response error: 404. How can the Verify feature be used correctly?

**Comment by quetool** [comment]
In any case you can disregard any verification exception log and just rely on what you see on the `onSessionProposal` event with `verifyContext`, (see here https://docs.walletconnect.com/web3wallet/verify?platform=flutter#implementation) but for the sake of information, getting a 404 it means that the dapp haven't set the attestation and can not be verified through our service. So the dApp could be or not be malicious.

**Comment by quetool** [comment]
For instance, you can test the different responses by scanning this verified as safe dapp https://react-app.walletconnect.com and this verified as malicious dapp https://malicious-app-verify-simulation.vercel.app

**Comment by damaxi1010** [comment]
Thank you for your response. The dapps I'm using are Uniwap and OKX. I thought both of these major dapps were verified through service.
