### ISSUE TITLE
How to handle this type of WC link.

### ISSUE THREAD

**Issue by damaxi1010** [WalletConnect/WalletConnectFlutterV2#234]
When using some dapps, I encounter instances where the dapp sends me this type of WC link "wc:86190be7417c75e1bf20cf7e93d2891cfa1135e9073ef456fd3bb20627eb0d7c@2/wc?requestId=1695275964670634&sessionTopic=d112e4e1ff1ec1918abf2ae28330bc7d5c402393aa6744a9ab7009a07512472b". I apologize for not being able to provide a specific dapp due to intermittent occurrences over a long period. After reviewing the official documentation several times, I am still uncertain about how to handle it.

**Comment by quetool** [comment]
Hello @damaxi1010! That seems to be a sign request link. In theory you can just disregard this kind of link as if you registered for events you should receive a session_request event with the proper sign request data. https://specs.walletconnect.com/2.0/specs/clients/sign/session-events
 
So basically:

1. When a dapp wants to Sign something, the wallet could be opened with that sort of deep link you shared.

2. However, wallet could disregard that URI in the deep link and instead listen/wait for a `session_request` event

3. When this event comes, could be a good idea to check if the topic on the session_request event matches the topic in the deep link URI (just to be sure you are handling the request you are indeed expecting but this is pretty much optional step)

**Comment by damaxi1010** [comment]
Thank you for your response.

**Comment by quetool** [comment]
No worries, @damaxi1010! Feel free to open a new issue if any! Thanks!
