### ISSUE TITLE
[chainChanged] - wcClient.emitSessionEvent() does not trigger

### ISSUE THREAD

**Issue by Fabrice-Fabio** [WalletConnect/WalletConnectFlutterV2#235]
Title: Issue with Network Change Trigger on DApp (PancakeSwap/Uniswap)

Description:

I would like to implement a feature where changing the chain on my wallet triggers a corresponding action on the DApp (like PancakeSwap or Uniswap).

To achieve this, I have a function _onChangeNetwork():

```
void _onChangeNetwork(String newNetwork) async {
  this.setState(() {
    _currentNetworkId = constants.networks[newNetwork]['networkId'];
  });

  await wcClient.emitSessionEvent(
    topic: currentSession!.topic,
    chainId: '$namespace:$_currentNetworkId',
    event: SessionEventParams(
      name: 'chainChanged',
      data: 'a message!',
    ),
  );
}
```

However, when I use currentSession, the DApp does not receive any event that could trigger the chain change.

I have configured my wallet as follows:

```
wcClient.registerEventEmitter(
  chainId: '$namespace:$_currentNetworkId',
  event: 'chainChanged',
);

wcClient.registerEventEmitter(
  chainId: '$namespace:1',
  event: 'chainChanged',
);

wcClient.registerEventEmitter(
  chainId: '$namespace:56',
  event: 'chainChanged',
);

wcClient.registerEventEmitter(
  chainId: '$namespace:42161',
  event: 'chainChanged',
);
```

Do I need to add anything else, or perhaps change the data in wcClient.emitSessionEvent?

Thank you for your assistance.

Also, does the same process apply for the accountsChanged event?

**Comment by quetool** [comment]
Hello @Fabrice-Fabio! I'm really sorry, I must have overlooked this issue! I read it just now.

If I get it right you are developing a wallet, right? And when you change the network in the wallet you want the dapp to listen to that change, is that correct?

As a wallet you must register an eventEmitter, for instance:

```dart
wallet.registerEventEmitter(
  chainId: '1',
  event: 'chainChanged,
);
```

Then use `emitSessionEvent`.

If this doesn't help, could you provide a complete reproducible example? Thanks!

**Comment by Fabrice-Fabio** [comment]
Hello @quetool , yes that's what i want to do.
- When i change network in the wallet, i want the dapp to listen to that change too.
- And i also want to listen network change from dapp, for example, if i change network from dapp, i want to listen this change in my wallet. How can i do it please ?

Thanks

**Comment by quetool** [comment]
Hello @Fabrice-Fabio! At first glance I see a few things:

1. chainId in registerEventEmitter must be with eip155:id format.

For instance:
```dart
wcClient.registerEventEmitter(
  chainId: 'eip155:10',
  event: 'chainChanged',
);
```

2. in your `emitSessionEvent` the data: value of the `SessionEventParams` must be the chainId with no eip155 as integer and not the current one, the one you are switching to:

For instance, if you are switching to polygon:
```dart
void _onChangeNetwork(String newNetwork) async {
    await wcClient.emitSessionEvent(
      topic: currentSession!.topic,
      chainId: 'eip155:137',
      event: SessionEventParams(
        name: 'chainChanged',
        data: 137,
      ),
    );
  }
```

-------------------------------------------

As a generic explanation:

A) How to receive chainChanged events on dapp?:

First register an event handler for `chainChanged` for every chain you want to handle (Example for main net):

```dart
_web3App!.registerEventHandler(chainId: 'eip155:1', event: 'chainChanged');
```

Then subscribe to `onSessionEvent` (the wallet you are connecting to must support `chainChanged` event and emit it):

```dart
_web3App!.onSessionEvent.subscribe(_yourHandler);
```

You would then receive an event such as the following when the connected wallet changes the network:

```dart
SessionEvent(id: 1704796411691549, topic: 8af1b3a72b28396b80328b186facc2a3e564301732141222d62724c486c99c0d, name: chainChanged, chainId: eip155:1, data: 1)
```

B) Wallets can not receive `chainChanged` events as this is an event emitted FROM wallets, not to wallets. So when you switch to a chain in your dApp two things could happen:

1. The selected chain is already approved by the wallet (most wallets case), then switch is immediate.
2. The selected chain is not approved (added) by the wallet (typically the case for Metamask), so and `add_ethereumChain` method should be requested to the wallet, upon approval, the switch should be done.

C) How to emit `chainChanged` events from the wallet:

First register an event emitter for `chainChanged` for every chain you want to support (Example for main net):

```dart
_web3wallet!.registerEventEmitter(chainId: 'eip155:1', event: 'chainChanged');
```

Then emit `chainChanged` event as follows (the dapp you are connected with must have registered and event handler for chainChanged):

```dart
_web3Wallet!.emitSessionEvent(topic: sessionTopic,
                             chainId: 'eip155:1',
                               event: const SessionEventParams(
                                	name: 'chainChanged',
                                	data: 1,
                              	),
                            );
```

**Comment by Fabrice-Fabio** [comment]
So if I understand correctly, the 'chainChanged' should only be triggered from the wallet to the dapp and not from the dapp to the wallet?
And by default it would be necessary to approve the chains taken into account by the dapp?

And to do this I can only configure my wallet. The whole part of the dapp must be managed equally.
Do you have a dapp that takes 'chainChanged' into account? I tried on pancakeswap and paraswap to change the network from my wallet, but it did not seem to be taken into account and to change the interface directly

**Comment by quetool** [comment]
> So if I understand correctly, the 'chainChanged' should only be triggered from the wallet to the dapp and not from the dapp to the wallet?

That is correct, the wallet emits chainChanged, the dapp listen to it.

> And by default it would be necessary to approve the chains taken into account by the dapp?

Not sure what you mean "by default". As a wallet you should approve those chains you support methods and events for.

> And to do this I can only configure my wallet. The whole part of the dapp must be managed equally.

That is correct, as a wallet you should configure it as you please, later when a dapp requests for namespaces approvals, your wallet will approve only those ones that supports.

> Do you have a dapp that takes 'chainChanged' into account? I tried on pancakeswap and paraswap to change the network from my wallet, but it did not seem to be taken into account and to change the interface directly

Our demo dApp under example/dapp should work just fine for that kind of tests.
You can see here how we register the event handlers https://github.com/WalletConnect/WalletConnectFlutterV2/blob/master/example/dapp/lib/main.dart#L88
And here the onSessionEvent handler definition https://github.com/WalletConnect/WalletConnectFlutterV2/blob/master/example/dapp/lib/main.dart#L261

**Comment by Fabrice-Fabio** [comment]
Okay thanks,
It's more clear.

But i've notice that "wallet_switchEthereumChain" doesn't work with walletconnectv2 right ?

My wallet is on the ETH chain and I connect to paraswap.
When I change the chain from the paraswap dapp, it triggers the "wallet_switchEthereumChain" event, but the latter is not triggered as an event by the wallet, is it taken into account in v2 or not please?

Is it possible to have a namespace configuration like this:
https://specs.walletconnect.com/2.0/specs/clients/sign/namespaces

**Comment by quetool** [comment]
> When I change the chain from the paraswap dapp, it triggers the "wallet_switchEthereumChain" event, but the latter is not triggered as an event by the wallet, is it taken into account in v2 or not please?

What do you mean exactly? I you request to change the network on ParaSwap then ParaSwap is the one that should request for `wallet_switchEthereumChain` TO YOUR WALLET. Your wallet needs to catch it with `onSessionRequest` event, change the network and then emit `chainChanged`.

The rule of thumb is:
A dapp requests for methods and receives events
A wallet receives methods and emits events

> Is it possible to have a namespace configuration like this:
> https://specs.walletconnect.com/2.0/specs/clients/sign/namespaces

Not sure what you mean here either. Namespaces object is a standard CAIP object for every platform.

**Comment by Fabrice-Fabio** [comment]
Yes that’s what I want.

Step 1 :
I got my wallet.
I connect my wallet to dapp (paraswap) for example.
I’m connected on chainId 1 (ETH)

Step 2 :
I change networkId on dapp from 1 to 137

Step 3 :
I want to catch this methods (‘wallet_switchEthereumChain’) and change ChainId on my wallet.

Code : 

```dart
wcClient.registerRequestHandler(
  chainId: '$namespace:$_currentNetworkId',
  method: 'wallet_switchEthereumChain',
  handler: switchEthChain
);
```

```dart
switchEthChain(String topic, dynamic parameters) async {
  String message = parameters;
  print("topic : $topic");
  print("parameters : $parameters");

  await wcClient.emitSessionEvent(
    topic: currentSession!.topic,
    chainId: 'eip155:137',
    event: SessionEventParams(
      name: 'chainChanged',
      data: 137,
    ),
  );
}
```


This is what my current code looks like, but it doesn't work.

**Comment by quetool** [comment]
`wcClient.registerRequestHandler` should be called for every chain you want to support the network change. Not the current chain. So in your case it should be

```dart
wcClient.registerRequestHandler(
  chainId: 'eip155:137',
  method: 'wallet_switchEthereumChain',
  handler: switchEthChain
);
```
