### ISSUE TITLE
Request eth_chainId only resolved when redirect to wallet app

### ISSUE THREAD

**Issue by mthinh** [WalletConnect/WalletConnectFlutterV2#237]
# What ?
I wanna get current chainId on wallet app (metamask), so I request 
```
Future<void> getCurrentWalletChainId() async {
    final activeSession = await getActiveSession();
    final walletChainId = await _app!.request(
      topic: activeSession.topic,
      chainId: _currentWalletChainId ?? WCUtils.getSessionsChains(activeSession.namespaces).first,
      request: const SessionRequestParams(
        method: 'eth_chainId',
        params: [],
      ),
    );
  }
```
  
  The thing is the future only resolved when I switch to metamask app, is there any way that do not require to redirect to metamask as this confuses the user

**Comment by quetool** [comment]
Hello @mthinh ! I suppose we can close this issue in favor of this other one. https://github.com/WalletConnect/WalletConnectFlutterV2/issues/238

Please don't hesitate to open a new one if you need to. Thanks!
