### ISSUE TITLE
How to calculate  gas fee before transaction

### ISSUE THREAD

**Issue by Asadu43** [WalletConnect/WalletConnectFlutterV2#241]
I want to calculate gas fee of transaction  Or I want to know how to estimate gas fee before transaction

**Comment by quetool** [comment]
Hello @Asadu43, that's out of our scope as it is not dependent of our SDK. You can check this article from MM but the web is plenty of them https://support.metamask.io/hc/en-us/articles/360059562111-How-to-estimate-the-gas-fee
