### ISSUE TITLE
Unsupported methods. onSessionProposeRequest namespaces methods don't satisfy

### ISSUE THREAD

**Issue by anhntn-paditech** [WalletConnect/WalletConnectFlutterV2#242]
I get this error when using My Wallet scan QR to connect.

Error in web3 dapp
**Unsupported methods. onSessionProposeRequest namespaces methods don't satisfy requiredNamespaces methods for eip155. Requested: [eth_sendTransaction, eth_signTypedData_v4, personal_sign], Supported: []**

- Error from IDE : 
[Web3WalletCubit] _onSessionProposalError SessionProposalErrorEvent(id: 1704339406502872, requiredNamespaces: {eip155: RequiredNamespace(chains: [eip155:1], methods: [eth_sendTransaction, eth_signTypedData_v4, personal_sign], events: [chainChanged, accountsChanged])}, namespaces: {eip155: Namespace(accounts: [eip155:1:0x5b1b882e64e0a06d2b59fdbdca1e5fc74e3b1442], methods: [], events: [])}, error: WalletConnectError(code: 5101, message: Unsupported methods. onSessionProposeRequest namespaces methods don't satisfy requiredNamespaces methods for eip155. Requested: [eth_sendTransaction, eth_signTypedData_v4, personal_sign], Supported: [], data: null))

**Smartphone :**
 - Device: XIAOMI REDMI 12
 - OS: ANDROID
 - walletconnect_flutter_v2 : 2.0.0

**Additional context**

**Comment by quetool** [comment]
Hello @anhntn-paditech, please try to send every namespace as optionalNamespace rather than differentiating between required and optional and let me know.

**Comment by anhntn-paditech** [comment]
@quetool 
Thank you for your answer
But I think there is confusion. I want to add a connect wallet feature to my wallet application, not that I want to build a dapp.

**Comment by anhntn-paditech** [comment]
@quetool 
oh, thank you very much
I think this is the problem. I will try it and get back to you later.

**Comment by quetool** [comment]
Please feel free to reopen if the issue persists. Thanks!
