### ISSUE TITLE
in wallet side i cant change wallet account

### ISSUE THREAD

**Issue by yyzfish** [WalletConnect/WalletConnectFlutterV2#252]
i use flutter codding,here is my code, i try to use updateSession to change my wallet account ,but not functional.
 
  Future<void> onUpdateSession(Map<String, Namespace> namespace) async {
    if (_web3Wallet == null) {
      Log.d('实例未初始化');
      return;
    }
    var activeSession = _web3Wallet!.getActiveSessions();

    await _web3Wallet!
        .updateSession(topic: activeSession.keys.first, namespaces: {
      'eip155': Namespace(accounts: [
        'eip155:5:0x523ed38edecbede0fc1d59bff167aa1a4c956702',
        'eip155:5:0x224f555ba3a8cfd8886ade93189a0005e53bfc00',
      ], methods: [
        'eth_sendTransaction',
        'personal_sign'
      ], events: [
        'chainChanged',
        'accountsChanged'
      ])
    });
  }

**Comment by quetool** [comment]
Hello @yyzfish, you can not change your active "wallet account" from your dapp. That's not an ethereum feature, it's up to the wallets (such Metamask or whatever other you use) to enable this possibility.
