### ISSUE TITLE
Does this library support flutter web platform?

### ISSUE THREAD

**Issue by yuanxintaxon** [WalletConnect/WalletConnectFlutterV2#259]
Hi does this library support flutter web platform?

**Comment by quetool** [comment]
Hello @yuanxintaxon! Not yet, we are working on it, we don't have an ETA but hopefully soon enough!

**Comment by quetool** [comment]
Hello @yuanxintaxon, web support is out in beta https://pub.dev/packages/walletconnect_flutter_v2/versions/2.2.3-beta01
