### ISSUE TITLE
Version 1.0.4 breaks because it lacks some generated files

### ISSUE THREAD

**Issue by mik3mast3rs** [WalletConnect/WalletConnectFlutterV2#26]
`../../AppData/Local/Pub/Cache/hosted/pub.dev/walletconnect_flutter_v2-1.0.4/lib/apis/core/relay_client/relay_client_models.dart(4,6): error GBB7C8005: Error when reading '../../AppData/Local/Pub/Cache/hosted/pub.dev/walletconnect_flutter_v2-1.0.4/lib/apis/core/relay_client/relay_client_models.g.dart': The system cannot find the file specified. `

The stack trace is longer. Mostly about lack of generated files.

**Comment by Luzzotica** [comment]
Yep. Fixing it now.

I'm new to this, i didn't think it would pass the tests but not include the generated files...
