### ISSUE TITLE
ios web browser can't work

### ISSUE THREAD

**Issue by cheekiat** [WalletConnect/WalletConnectFlutterV2#260]
hi, i using android web browser is working, but ios web browser can't work, have any solution?

**Comment by quetool** [comment]
Hello, web is not fully supported yet, we are working on it! Thanks!

**Comment by cheekiat** [comment]
Thank you for your response, may I know around how long can done and
release?

**Comment by quetool** [comment]
Hello @cheekiat! Hopefully during this first quarter!

**Comment by quetool** [comment]
Hello @cheekiat ! Web support is out on beta release https://pub.dev/packages/walletconnect_flutter_v2/versions/2.2.3-beta01
