### ISSUE TITLE
SessionEvent data is only string other langue is dynamic

### ISSUE THREAD

**Issue by cp-byungsun** [WalletConnect/WalletConnectFlutterV2#272]
**Describe the bug**

SessionEvent data is just a string, other languages ​​are dynamic. When delivering an event, it does not work properly.

**Comment by quetool** [comment]
Not sure what you mean or what's your issue but `data` in `SessionEvent` is dynamic https://github.com/WalletConnect/WalletConnectFlutterV2/blob/master/lib/apis/sign_api/models/sign_client_events.dart#L161

**Comment by cp-byungsun** [comment]
sorry. This issue is a Kotlin issue. I didn't look at the repository clearly.
