### ISSUE TITLE
Not connecting with Uniswap

### ISSUE THREAD

**Issue by muhammad-hassan-shakeel** [WalletConnect/WalletConnectFlutterV2#273]
<img width="345" alt="image" src="https://github.com/WalletConnect/WalletConnectFlutterV2/assets/42541154/976ceeb9-76d5-4894-849d-abe79dc1a8c9">

When I try to connect with Uniswap, I get this message. Please let me know how to resolve this.

**Comment by quetool** [comment]
Hello @muhammad-hassan-shakeel , the error is pretty self-explanatory. Apparently Uniswap does not support `personal_sign` method. You are requesting `eth_sendTransaction` and `personal_sign` methods but Uniswap supports `eth_sendTransaction`, `eth_sign`, `eth_signTypedData` and `eth_signTypedData_v4`.

The solution on your side is to requests every methods as `optionalNamespace` and leave `requiredNamespaces` blank
