### ISSUE TITLE
Register and unregister from echo server throws HandshakeException

### ISSUE THREAD

**Issue by Volfor** [WalletConnect/WalletConnectFlutterV2#274]
**Describe the bug**
I've setted up WalletConnect push notifications with Firebase. 
Calling `web3Wallet.core.echo.register(fcmToken);` or `web3Wallet.core.echo.unregister();` throws the HandshakeException:
```dart
HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: Hostname mismatch(handshake.cc:393))
```

**Smartphone:**
 - Devices: OnePlus 5T / iPhone 12
 - OS: Android 10 / iOS 17.3.1

**Additional context**
This is a wallet app.
walletconnect_flutter_v2: ^2.2.1

**Comment by quetool** [comment]
Hello @Volfor ! Apologize for the delay! Push Notifications is still not fully implemented. You can track this issue for following updates https://github.com/WalletConnect/WalletConnectFlutterV2/issues/254
