### ISSUE TITLE
tron_signTransaction JsonRpcError(code: 5201, message: Unknown method(s) requested)

### ISSUE THREAD

**Issue by AmjadKhan2k18** [WalletConnect/WalletConnectFlutterV2#279]
**Describe the bug**
I have connected Tron network on TrustWallet but can't sign transaction, I am getting error
```
sonRpcError(code: 5201, message: Unknown method(s) requested)
```
is there any example available in flutter except EVM chains? 
I tested the web example of dapp from WalletConnect V2 and I was able to see sign transaction in TrustWallet but doesn't work in Flutter, am I doing something wrong or anything missing ? if anyone have done sign transaction on tron chain Please share example 

method : `tron_signTransaction`
chain : `tron:0x2b6653dc`
params :` {from: TD7Ve4TigHpR4PzP6K5LFCyKsYBFRbApov, to: TQUiQy5Mdrdps8tTqj35WNHkVJCYjCsfvX, value: 0x16e364}`

when connecting I have provided `tron_signTransaction` method 
```
 optionalNamespaces: {
          'eip155': RequiredNamespace(
            chains: Web3Helper.getChains(wallet.web3Wallet),
            methods: Web3Helper.rpcOptionalMethods,
            events: Web3Helper.rpcEvents,
          ),
          'tron': RequiredNamespace(
            chains: [
              "tron:0x2b6653dc",
            ],
            methods: ['tron_signTransaction', 'tron_signMessage'],
            events: [],
          ),
        },
```

**To Reproduce**
1 : connect Tron chain on trustwallet 
2 : sign transaction

**Reproducible code**
If applicable, add a minimum reproducible code snippet.

**Screenshots**
In Trustwallet I get unkown error occur 
![Screenshot_20240321-220124](https://github.com/WalletConnect/WalletConnectFlutterV2/assets/44894621/36ca90c5-eef4-4136-a337-8168d0e0f126)

**Desktop (please complete the following information):**
 - OS: Android
 - Version 33

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4
 - OS: Android 33

**Comment by quetool** [comment]
Hello @AmjadKhan2k18! Flutter SDK currently supports only EVM chains. We are working towards non-EVM chains but it might take some time.

**Comment by jay3024** [comment]
i same above explained error in react js 
{
    "code": 5201,
    "message": "Unknown method(s) requested"
}

and same "An unknown Error Occurred"  in trust wallet mobile

below is my function
const approveUSDT = async () => {
    if (!wallet) {
      console.error("Wallet is not initialized!");
      return;
    }
  
    try {
      // ✅ Initialize TronWeb instance
      const tronWeb = new TronWeb({
        fullHost: "https://api.trongrid.io", // Use Mainnet (or "https://api.shasta.trongrid.io" for testnet)
      });
  
      // ✅ Build the approval transaction correctly
      const transaction = await tronWeb.transactionBuilder.triggerSmartContract(
        tronWeb.address.toHex(USDT_CONTRACT), // Convert USDT contract address to hex
        "approve(address,uint256)",
        { feeLimit: 10000000 }, // Adjust gas limit if needed
        [
          { type: "address", value: SPENDER },
          { type: "uint256", value: AMOUNT },
        ],
        walletAddress // Sender's address
      );
  
      if (!transaction || !transaction.transaction) {
        console.error("Failed to build the approval transaction.");
        return;
      }
  
      console.log("Generated Transaction:", transaction);
  
      // ✅ Sign the transaction using WalletConnect
      const signedTx = await wallet.signTransaction(transaction.transaction);
  
      // ✅ Send the signed transaction to the TRON blockchain
      const txHash = await tronWeb.trx.sendRawTransaction(signedTx);
  
      console.log("Approval Transaction Hash:", txHash);
      alert(`Transaction Sent! Hash: ${txHash.txid}`);
    } catch (error) {
      console.error("Error in Approval Transaction:", error);
   
    }
  };

please any one knows reply me

**Comment by quetool** [comment]
Hello @jay3024, this repository is deprecated since a while now, please refer to https://github.com/reown-com

But also this si a Flutter repo and your issue is related to React JS.

I would advise you to first update to Reown's package and then open an issue over there if still needed: https://github.com/reown-com/appkit
