### ISSUE TITLE
Question: Opening Metamask on Flutter Web

### ISSUE THREAD

**Issue by andrewkimjoseph** [WalletConnect/WalletConnectFlutterV2#288]
How can I use this plugin to launch my Metamask extension on the browser?

**Comment by quetool** [comment]
Hello @andrewkimjoseph! Unfortunately for now you would need to leverage some other package such as [flutter_web3](https://pub.dev/packages/flutter_web3) or [webthree](https://pub.dev/packages/webthree)

`webthree` package example for web is here https://github.com/devopsdao/webthree/blob/master/example/metamask/web/main.dart

Bear in mind that once you use an injected connector/wallet the connection is not handled by WalletConnect
