### ISSUE TITLE
package_info_plus dependency outdated and creates resolving issue

### ISSUE THREAD

**Issue by kev-techi** [WalletConnect/WalletConnectFlutterV2#290]
**Describe the bug**

package_info_plus dependency creates issues because it is out of date.

```
Resolving dependencies... 
Because walletconnect_flutter_v2 >=2.2.3-beta01
  depends on package_info_plus ^7.0.0 and citizenwallet
  depends on package_info_plus ^8.0.0,
  walletconnect_flutter_v2 >=2.2.3-beta01 is forbidden.
So, because citizenwallet depends on
  walletconnect_flutter_v2 ^2.2.3, version solving
  failed.
```

**To Reproduce**
1. Install the latest version of package_info_plus
2. Install the latest version of walletconnect_flutter_v2
3. See error

**Expected behavior**
I expect to be able to install both packages.

**Comment by quetool** [comment]
Hello @kev-techi! This is pretty common in Flutter and I'd say the fix is pretty simple. Until we submit a new version with package_info_plus updated you can just override it.

```
dependencies:
  walletconnect_flutter_v2: ^2.2.3

dependency_overrides:
  package_info_plus: ^8.0.0
```
