### ISSUE TITLE
URI methods has double quoted strings which cause compatibility issues

### ISSUE THREAD

**Issue by bobwith2bees** [WalletConnect/WalletConnectFlutterV2#30]
The WalletConnect Pairing Uri's contain double quote marks around the sting methods. This is not part of the specification, and causes compatibility where the receiver may not treat the method strings a JSON encoded objects.

Pre-fix behavior: &methods=["wc_sessionPropose","wc_sessionRequest"]
New behavior: &methods=[wc_sessionPropose,wc_sessionRequest]

See the pairing URI's do not have quotes here:
https://docs.walletconnect.com/2.0/specs/clients/core/pairing/pairing-methods

PR: From https://github.com/WalletConnect/WalletConnectFlutterV2/pull/29

Workaround
```dart
    Uri? pairingUri = resp.uri;
    String decodedUriString = Uri.decodeFull(paringUri.toString());
    // print it before etc
    String removeQuotesFromUri = decodedUriString.replaceAll('"', '');
    pairingUri = Uri.parse(removeQuotesFromUri);
```

**Comment by Luzzotica** [comment]
Resolved by #28
