### ISSUE TITLE
Should be able to 'reconnect' to relay server

### ISSUE THREAD

**Issue by dmdeklerk** [WalletConnect/WalletConnectFlutterV2#31]
When the websocket connection goes down there should be a way to 'reconnect' to the relay server. 

Ideally (in the case of a wallet) when you create a Web3Wallet and its disconnected. 
You should be able to call a method which leaves in tact all the event listeners as well as all other configurations and simply sets up a new Websocket channel internally.

```
Web3Wallet.disconnect()

Web3Wallet.reconnect()
```

A second use case would be to use the disconnect/reconnect feature in integration testing.

**Comment by Luzzotica** [comment]
You can reconnect the Websocket using `wcClient.core.relayClient.connect();` if the connection does fail and you need it.

Perhaps need some documentation on this, or to pull the function up to the Web3Wallet level as you've described. 

What would you suggest? Where would you look for it?

**Comment by dmdeklerk** [comment]
As a wallet dev I would expect that when I create the `Web3Wallet` and listen to `wcClient.core.relayClient.onRelayClientDisconnect` I had some way to call `wcClient.core.relayClient.reconnect()` or something of that nature.

The `reconnect` method would use the relay url to connect to the most recent relay server and should subscribe to all topics again.
