### ISSUE TITLE
How to Connect with/Support/Manage Non-EVM chains (Bitcoin) after connecting with 3rd party wallets App

### ISSUE THREAD

**Issue by faaqi** [WalletConnect/WalletConnectFlutterV2#310]
**Describe the bug**
We integrated wallet connect in our app 1.5 years ago. Our wallet can connect with external web3 wallets and manage them in our app. The signing process happens at the external wallets app. The EVM chains are working fine. But we do need to handle non EVM chains like Bitcoin. Because it is important in terms of business point of view. Is there any support available? Any help will be appreciated. 

Also, Will walletconnect support Non EVM chains in future?

**To Reproduce**
1. Connect external wallet using wallet connect
2. Try to create bitcoin transaction
3. Non EVM chain not suported so invalid recipient address being generated in transaction

**Expected behavior**
Non EVM chains should also be handled 

**Additional context**
This is a more of discussion thread. Please feel free to ask questions.

**Comment by quetool** [comment]
Hello @faaqi! Thanks for the interest please refer to this discussion about Bitcoin! Thanks! https://github.com/WalletConnect/WalletConnectFlutterV2/discussions/309
