### ISSUE TITLE
[Feature Request] Need a better way to check projectId status

### ISSUE THREAD

**Issue by bobwith2bees** [WalletConnect/WalletConnectFlutterV2#32]
Perhaps this is something the WalletConnect team can do with the explorer API?  A simple HEAD request to provide the server response based on the provided projectId?

## Problem ##
Even if you plumb the RelayClient errors all the way out via rethrows and get the WalletConnect error 401 -  there are still multiple root causes (and remediations) for this error.   The underlying Websocket library does not forward the server response codes to the WalletConnect library.

### Blocking issue ###
https://github.com/dart-lang/web_socket_channel/issues/188

This prevents us from acting on the details documented here:
https://docs.walletconnect.com/2.0/cloud/relay#error-codes

## Why? ##
Well if my app is indeed making too many requests - the last thing I should do as a well behaved application is keep retrying.

**Comment by Luzzotica** [comment]
I agree with this, but with the current implementation, I'm honestly now sure how to achieve this.

The current websocket lib doesn't give me any errors other than: It failed!

Perhaps I could make an HTTPs request first, and then attempt the WebSocket?
Open to ideas of how to trigger errors on the projectId before we attempt a websocket connection.

**Comment by Luzzotica** [comment]
Resolved #52
