### ISSUE TITLE
[Feature Request] Ping the relay server / keep socket connection alive

### ISSUE THREAD

**Issue by dmdeklerk** [WalletConnect/WalletConnectFlutterV2#34]
Socket connections need to be kept alive. 
This is normally done through sending ping messages.

The way WebSocketChannel is setup currently 2 issues arise:

1. There seems to be no way to manually send ping messages `relayClient.socket.sink.add('ping')` gives error (StreamSink is bound to a stream)
2. WebSocketChannel can handle pings itself to keep the connection alive but [this feature](https://github.com/dart-lang/web_socket_channel/blob/a90e740dad4739d578e09eb0e076ac2846f9404e/lib/src/channel.dart#L106) is not used currently 

Can we get some way to keep the websocket connection alive?

**Comment by dmdeklerk** [comment]
On further inspection it turns out that if you **DONT** set _pingInterval_, on the IO versions of the ws client, it will **NOT** send ping messages to the server on an interval. So setting _pingInterval_ seems like an easy fix there.

However, the w3c standard says that browser ws clients **DO** send regular pings to their servers. So I expect the browser version not to run into this issue.

**Comment by Luzzotica** [comment]
Resolved with above
