### ISSUE TITLE
[Feature Request] Observable Sessions and Pairings

### ISSUE THREAD

**Issue by dmdeklerk** [WalletConnect/WalletConnectFlutterV2#35]
Can there be  someway to observe sessions and pairings?
We need to observe creation, updates and deletions.

Our use case is that we want to:

1. Show session and pairing info to the user and update the UI when there are new (or deleted) sessions or pairings or their properties change.
2. Persist session and pairing info in our data model

**Comment by bobwith2bees** [comment]
You can see SignClient.onSessionConnect  and SignClient.onSessionDelete callbacks fire in my debug.  

```dart
    _signClient.onSessionConnect.subscribe((SessionConnect? sessionConnect) {
      isSignClientUp = true;
      _topic = sessionConnect?.session.topic ?? 'none';
      logger.d('Updating topic to: $_topic');
      if (sessionConnect != null) {
        DateFormat dateFormat = DateFormat(kLogTimeStampFormat);
        String dateString = dateFormat.format(DateTime.now());

        logger.d('$dateString SignClient.onSessionConnect - $connectedSessionCount active sessions.');
        serviceStats.setSessionConnected(_topic);
        showSessionData(sessionConnect.session);
        return;
      }
      logger.d('SignClient.onSessionConnect - null data passed');
    });
```



```
I/flutter (15572): 💡  ExplorerRegSvc  - launchApp - 1. originalUri using LaunchMode.externalApplication 
I/flutter (15572): wc:3f90d8d91e326d8a3a958ee32e5b76584726da943f13c14eeaa7ce4db475e4da@2?relay-protocol=irn&symKey=4552509d92e7ab49bc894d054e8113aca42a1106128915325daa7c3306038d75&methods=[wc_sessionPropose,wc_sessionRequest]
I/flutter (15572): 🐛  WalletConnctSvc - createWalletConnectSession - launchAppWithParingUri returned true
I/flutter (15572): 🐛  WalletConnctSvc - createWalletConnectSession - Connection with wallet took 416656 microseconds.
I/flutter (15572): 🐛  WalletConnctSvc - =Sign Client Info - (wc v2)=
I/flutter (15572): 🐛  WalletConnctSvc - ==Sign Client Sessions (0)==
I/flutter (15572): 🐛  WalletConnctSvc - No sessions.
I/flutter (15572): 🐛  WalletConnctSvc - ==Sign Client Proposals (1)==
I/flutter (15572): 🐛  WalletConnctSvc -      4:59 topic: 3f90d8d91e326d8a3a958ee32e5b76584726da943f13c14eeaa7ce4db475e4da - required: [ eip155:137 ], optional: [  ], session properties: null, id: 1677273231846, relays: [ irn ], proposer: ATX DAO Demo App
I/flutter (15572): 🐛  WalletConnctSvc - ==Sign Client Stats== (topic: 6e8970ac5975174e095fa93f8e6f530d1ceadae0b31696a6672c46ca87574339
I/flutter (15572): 🐛  WalletConnctSvc - null
I/flutter (15572): 🐛  HomePage        - 15:09:13 AppLifecycleState: AppLifecycleState.inactive.
E/BLASTBufferQueue(15572): [ViewRootImpl[MainActivity]#6](f:0,a:1) Applying pending transactions on dtor 1
I/flutter (15572): 🐛  HomePage        - 15:09:20 AppLifecycleState: AppLifecycleState.paused.
I/flutter (15572): 🐛  WalletConnctSvc - Core.onRelayClientMessage  - topic: 3f90d8d91e326d8a3a958ee32e5b76584726da943f13c14eeaa7ce4db475e4da message: 292 bytes
I/flutter (15572): 🐛  WalletConnctSvc - Core.onRelayClientMessage  - topic: 12eaa7ff260a89963b5b4456e79aad2f6ba70c10df582801d0a74382290fa9d6 message: 1152 bytes
I/flutter (15572): 🐛  WalletConnctSvc - Updating topic to: 12eaa7ff260a89963b5b4456e79aad2f6ba70c10df582801d0a74382290fa9d6
I/flutter (15572): 🐛  WalletConnctSvc - 15:09:32 SignClient.onSessionConnect - 1 active sessions.
12eaa7ff260a89963b5b4456e79aad2f6ba70c10df582801d0a74382290fa9d6
I/flutter (15572): 🐛  WalletConnctSvc -     6 days topic: 12eaa7ff260a89963b5b4456e79aad2f6ba70c10df582801d0a74382290fa9d6 controller: f328b05bf5f708d340bd97801acb7307b1270334d3329a7781a04f9479eda742 ack: true,  requiredNamespaces: {eip155: Instance of 'RequiredNamespace'}, optionalNamespaces: null peer name: Keyring 
I/flutter (15572): 🐛  HomePage        - 15:09:42 AppLifecycleState: AppLifecycleState.resumed.
I/flutter (15572): 🐛  WalletConnctSvc - =Core Services (wc v2 crypto)=
I/flutter (15572): 🐛  WalletConnctSvc - Relay URL: wss://relay.walletconnect.org
I/flutter (15572): 🐛  WalletConnctSvc - ==Pairings (1)==
I/flutter (15572): 🐛  WalletConnctSvc - 29 days topic: 3f90d8d91e326d8a3a958ee32e5b76584726da943f13c14eeaa7ce4db475e4da, relay irn, active: true
I/flutter (15572): 🐛  WalletConnctSvc - =Sign Client Info - (wc v2)=
I/flutter (15572): 🐛  WalletConnctSvc - ==Sign Client Sessions (1)==
I/flutter (15572): 🐛  WalletConnctSvc -     6 days topic: 12eaa7ff260a89963b5b4456e79aad2f6ba70c10df582801d0a74382290fa9d6 controller: f328b05bf5f708d340bd97801acb7307b1270334d3329a7781a04f9479eda742 ack: true,  requiredNamespaces: {eip155: Instance of 'RequiredNamespace'}, optionalNamespaces: null peer name: Keyring 
I/flutter (15572): 🐛  WalletConnctSvc - ==Sign Client Proposals (0)==
I/flutter (15572): 🐛  WalletConnctSvc - No proposals.
I/flutter (15572): 🐛  WalletConnctSvc - ==Sign Client Stats== (topic: 12eaa7ff260a89963b5b4456e79aad2f6ba70c10df582801d0a74382290fa9d6
I/flutter (15572): 🐛  WalletConnctSvc - messageCount: 0 (0 bytes), errorCount 0, pings(TX/RX): 0/0, expireCount: 0, extentCount: 0, connectTime: 15:09:32, deleteTime: null
I/flutter (15572): 🐛  HomePage        - 15:11:36 AppLifecycleState: AppLifecycleState.inactive.
I/flutter (15572): 🐛  HomePage        - 15:11:37 AppLifecycleState: AppLifecycleState.paused.
I/flutter (15572): 🐛  WalletConnctSvc - Core.onRelayClientMessage  - topic: 12eaa7ff260a89963b5b4456e79aad2f6ba70c10df582801d0a74382290fa9d6 message: 200 bytes
I/flutter (15572): 🐛  WalletConnctSvc - Core.onRelayClientMessage  - topic: 3f90d8d91e326d8a3a958ee32e5b76584726da943f13c14eeaa7ce4db475e4da message: 200 bytes
I/flutter (15572): 🐛  WalletConnctSvc - 15:11:42 SignClient.onSessionDelete  - topic: 12eaa7ff260a89963b5b4456e79aad2f6ba70c10df582801d0a74382290fa9d6 id: 1677273100745511
I/flutter (15572): 🐛  HomePage        - 15:11:48 AppLifecycleState: AppLifecycleState.resumed.
I/OpenGLRenderer(15572): Davey! duration=126394ms; Flags=1, FrameTimelineVsyncId=9368981, IntendedVsync=741175596680128, Vsync=741175596680128, InputEventId=500383379, HandleInputStart=741175597196323, AnimationStart=741175597200750, PerformTraversalsStart=741175597201844, DrawStart=741175611476845, FrameDeadline=741175630013460, FrameInterval=741175597184917, FrameStartTime=16666666, SyncQueued=741175611839450, SyncStart=741175611905543, IssueDrawCommandsStart=741175611986689, SwapBuffers=741175615878304, FrameCompleted=741301990933550, DequeueBufferDuration=2559219, QueueBufferDuration=421459, GpuCompleted=741301990933550, SwapBuffersCompleted=741175616638252, DisplayPresentTime=498216206482, 
I/flutter (15572): 🐛  WalletConnctSvc - =Sign Client Info - (wc v2)=
I/flutter (15572): 🐛  WalletConnctSvc - ==Sign Client Sessions (0)==
I/flutter (15572): 🐛  WalletConnctSvc - No sessions.
I/flutter (15572): 🐛  WalletConnctSvc - ==Sign Client Proposals (0)==
I/flutter (15572): 🐛  WalletConnctSvc - No proposals.
I/flutter (15572): 🐛  WalletConnctSvc - ==Sign Client Stats== (topic: 12eaa7ff260a89963b5b4456e79aad2f6ba70c10df582801d0a74382290fa9d6
I/flutter (15572): 🐛  WalletConnctSvc - messageCount: 0 (0 bytes), errorCount 0, pings(TX/RX): 0/0, expireCount: 0, extentCount: 0, connectTime: 15:09:32, deleteTime:  15:11:42
```

**Comment by bobwith2bees** [comment]
@dmdeklerk - I should note that I am blindly guessing and hooking any callbacks I can find.   My use may not be the sanctioned (or most efficient use) but I am sharing what I have.  I'll look at the session saving next, as there was a change log recently that mentioned that.  
https://pub.dev/packages/walletconnect_flutter_v2/changelog#108

**Comment by dmdeklerk** [comment]
@bobwith2bees thats my point indeed. All models are persisted to storage and if there could be a hook of some sort to observe storage that would cover the need to keep a UI connected model in sync.

We are using https://mobx.netlify.app/ for UI state management for instance and being able to update our models on each write to storage would be sufficient.

**Proposal** 

Allow a user provided IStore interface to be passed when constructing the Core class. 
https://github.com/WalletConnect/WalletConnectFlutterV2/blob/1a643efc3b9f3e5059fa9994bedfbb1f198f7642/lib/apis/core/core.dart#L44-L54

**Comment by Luzzotica** [comment]
This can effectively be done already using the built in events as they exist.

The `onSessionConnect`, `onSessionDelete`, `onSessionExpire`, `onSessionExtend`, `onSessionProposal`, `onSessionRequest`, and `onSessionUpdate` can be used to update UI values you are displaying to the user. Whether that be adding a Session, removing it, changing its displayed expiry time, showing proposals, etc. 

For the pairings, you have similar events: `onPairingDelete`, `onPairingInvalid`. When you call the create or pair functions, a new pairing is created automatically for you (If the function succeeds), and you can use the response to populate UI.

Does that clear things up? 

I'd prefer to stick with the current approach of setting up a different event for each of these things, but I'm not opposed to option 2 though, if we really feel it's necessary.

**Comment by dmdeklerk** [comment]
Thank you @Luzzotica that does seem to match the requirement. I'll come back to you if we run into anything related to this subject.

**Comment by dmdeklerk** [comment]
@Luzzotica it appears that its difficult to keep the reactive model in sync through events. 
As not every update to the WC V2 model objects results in an event being broadcasted.

It remains that this solution seems to be simplest and catch all solution.

```dart
class SharedPrefsStores implements IStore<Map<String, dynamic>> {
  @override
  final Event<StorageEvent> onStorageUpdate = Event<StorageEvent>();
}
```

Can we reopen this issue for that event?

**Comment by Luzzotica** [comment]
K, I'll take a look at adding the catch all and create more a spec for it.

I haven't seen any of the other repos do this, and I'd like to stay in sync with them as much as possible.

What WCv2 objects get updated without an event?

**Comment by dmdeklerk** [comment]
> I haven't seen any of the other repos do this, and I'd like to stay in sync with them as much as possible.

Well you could always improve things 😉 just as Flutter is an improvement over native Swift or Kotlin or ReactJS 🤓.

In our case we use Mobx, but for general Flutter development which uses setState() having one single method that indicates any of the WCv2 objects changed state is by far the easiest way to trigger a screen repaint. 

And considering you are already doing a serialisation to json AND an async write to the storage, I guess a quick call to repaint a screen from memory objects is a no brainer.

> What WCv2 objects get updated without an event?

At least Pairing creation and I've observed some other parts in code that do end in a call to write to the SharedPreferences but trigger no more events.

**The ideal implementation**

The ideal implementation would be if we could observe every time a `persist` is called (which in turn signals the model was updated) looking here these are not that many places
https://github.com/search?q=repo%3AWalletConnect%2FWalletConnectFlutterV2%20persist()&type=code 

Do note that this feature will be very useful for both reactive wallet apps as well as dapps.

**Comment by bobwith2bees** [comment]
A comment on leaning heavily on events to understand the state.   

There are already events that I miss due to race conditions ( e.g. SignClient.createInstance creates a new Core instance which connects to the Relay before a user can register for the relay.OnConnect callback -  so I miss the first one.)

My concerns are when the app is offline for a long period of time, and the app is started fresh.   There may be additional events fired before I can register them.  I would rather not have to parse the relay history and my own app cached version of session state to make an educated guess on what happened.  (Disappearing sessions without context is a bad user experience.)

From my router days I am used to setting the configuration first, then telling the protocol to start when everything is ready.  I have no idea what the new kids are doing these days.  hah!

**Comment by dmdeklerk** [comment]
> There are already events that I miss due to race conditions ( e.g. SignClient.createInstance creates a new Core instance which connects to the Relay before a user can register for the relay.OnConnect callback - so I miss the first one.)

We create the Core, subscribe to the relay events. Then pass the Core instance to the Web3Wallet constructor. This gets you onConnect.

**Comment by Luzzotica** [comment]
@dmdeklerk What updates to the model have you seen that that don't have an associated event?

**Comment by Luzzotica** [comment]
`Pairing.pair` returns data you can use to update your UI, `Pairing.create` does not. This is an oversight and I'll fix it right now.
I could see it being beneficial to have an event the is emitted when a pairing is created though. This would be helpful for a reactive UI when things are created. 

`Pairing.init` with cleanup is only at startup, so I don't care too much about that. 
I assume that you will query the current state of things once the client has been initialized, and I don't think that is a false assumption to make. 

Personally, I don't care for you to have access to authKeys nor pairing topics directly. The values there are (Honestly) not helpful to any user, and meant for internal use only (They are hashes of private keys). You can query the list of PairingInfo if you really want that, and there are events emitted when those are deleted/expired, and as I stated above, the PairingInfo is made available to you when you call the corresponding function.

For me it's a question of "Can I show the user what they need to know?"
And right now my answer to that question is. 
HOWEVER, I haven't built the example wallet yet. My opinion on the matter may change.

So, a better question than the one I posed above:
What information are you presenting to your user that doesn't have an associated event already for a reactive UI?

There are multiple reasons I don't want to create a catchall event:

1. Some of the data that exists should be hidden from the user, such as the private keys that are generated for a pairing and a session. I don't want you displaying those to your user (Even though right now you can if you drill down to the crypto keys).
2. I see a catchall potentially being the lazy approach from a UI perspective. If I am redrawing my screen every time data is stored/updated I feel like that would decrease the responsiveness of my app.

Number 1 is something I don't want anyone to have access to, and thus a catchall is a bit... too much.
Number 2 can be resolved if I build the event right so you can detect the piece of the app that changed, and the dApp/Wallet builder makes sure they only redraw the portions of the screen that really need it.

My thought after typing all of this up is this:
Put an event in the storage mechanisms that are built on top of the SharedPrefs storage.
So, there would be an event in the pairings storage, the sessions storage, etc. that would make it easier to catch all state updates to those specific items. 
This would be similar to a catch all, but only for that piece of the state.
It would remove the issue of problem number 1. 
And it would resolve problem number 2.

I'm open to feedback on any/all of my points above.

**Comment by Luzzotica** [comment]
#43 Adds additional events for you to listen to.

It doesn't have a catch all, but it should help you update UI when pairings are created.

**Comment by dmdeklerk** [comment]
> What information are you presenting to your user that doesn't have an associated event already for a reactive UI?

I want to show the user in the Wallet Connect section under "Active connections" whats going on re the various connections plus offer commands like disconnect, ping, extend expiry. We are just showing every property of every session and pairing there now, which will end up in the final product we are not sure of yet. 
We dont really care which event changes anything to change in the WCv2 model objects, just that if they change we trigger a screen repaint. Now we subscribe to pretty much every event available. 

> I see a catchall potentially being the lazy approach from a UI perspective. If I am redrawing my screen every time data is stored/updated I feel like that would decrease the responsiveness of my app.

My reasoning here is that screen repaints are quick (and debounced in our case) serialising big parts of the model to a json string and writing those to storage however are more costly. And thats what happens already. In my opinion the responsiveness is not affected.

> So, there would be an event in the pairings storage, the sessions storage, etc.

Yes this was the idea we had, its more work for you than the single catch all event. But its better, thank you we will use this. For triggering setState() this will be great.
