### ISSUE TITLE
[Question] How to match Session -> PairingInfo

### ISSUE THREAD

**Issue by dmdeklerk** [WalletConnect/WalletConnectFlutterV2#36]
[From a Wallet perspective]

Is it correct that every session belongs to 1 pairing?
If so it would make sense to group sessions per pairing when displaying these in UI.

- Pairing 1
   - Session 1
   - Session 2
 - Paring 2
   - Session 3
   - Session 4

How does one find which session belongs to a pairing and vice versa?

**Comment by Luzzotica** [comment]
At the current point in time, there isn't a direct link between the two.

Which leads to errors like: If I delete a pairing, the sessions that are using it are not deleted.

This is something I've thought about though, and I am building a plan to implement it.
As of right now, none of the other WalletConnect libs have a link between the two (That I'm aware of).

**Comment by dmdeklerk** [comment]
It seems there is a mention of it here https://github.com/WalletConnect/WalletConnectKotlinV2/issues/618

**Comment by dmdeklerk** [comment]
Everything written here is from the perspective of a user of Web3Wallet.

When we call core.pairing.disconnect(topic: pairingInfo.topic) the Pairing is removed.
All sessions however remain in place. 

When the dapp sends a request after we disconnected the pairing, the request arrives at the wallet client. 
A ping from dapp to wallet works.

When we shutdown the app and relaunch it. 
1. The pairing is still gone, the session however is present, its restored.
2. The session can receive events from the dapp

So how is this supposed to work? 

**Question** 

How as a wallet developer, do I disconnect the user from a dapp? 
And how do I cleanup after the user disconnects?

**Comment by Luzzotica** [comment]
Hmmm, with the pairing gone, the session shouldn't be able to communicate anymore.
This sounds like a bug on my part, I'm likely not deleting the symKey that's allowing it to communicate properly.

Also, based on that issue: https://github.com/WalletConnect/WalletConnectKotlinV2/issues/618

I will put the pairing topic into the SessionData, and create the `getActiveSessionByTopic` function as they have it in theirs that will either get you a single SessionData if you passed in a Session Topic, or all of the Sessions associated with a PairingTopic.
