### ISSUE TITLE
Missing implementation for Pairing.updateExpiry

### ISSUE THREAD

**Issue by dmdeklerk** [WalletConnect/WalletConnectFlutterV2#41]
When we call Pairing.updateExpiry no event is send to the JsonRpc server.
Also when an invalid expiry value is provided there should be an error at the library level.

Extra note. When invalid expiry value is provided to this method it will be persisted to storage. However when you relaunch the app the value is found to be invalid to be used as a millisecondsSinceEpoch seed as its too big and the app will crash as a result.

**Comment by Luzzotica** [comment]
On it.

**Comment by Luzzotica** [comment]
Looking at the other repo's code, I believe this is actually on purpose.

That function is meant to be used to update the expiration of a pairing internally, not for you to update the pairing's expiration.

This is rather misleading, and I'll see if my assumption is actually correct.

As for the ability to crash your system by inputting an out of range value, that's not quite right. I'll add a validation for the expiration.

**Comment by Luzzotica** [comment]
Can you give me an example of "too big"?

The expiry is meant to be in seconds (According to my notes).

**Comment by Luzzotica** [comment]
#43 Checks that the pairing expiry is not greater than 30 days away, which should solve the problem with invalid times (Maybe I should check that it's greater than the current time too...)

I have created a PR in the docs for the wc_pairingExtend: WalletConnect/walletconnect-docs#536

**Comment by dmdeklerk** [comment]
> Can you give me an example of "too big"?

I cant recall exactly what the number was. But as you understood what happened was that some big number was successfully persisted to storage. But when the storage was read on startup that number was considered to be too big to be anything valid to be used as a millisecond timestamp, and thus it throwed some exception.

**Comment by Luzzotica** [comment]
So the current implementation of `updateExpiry` is actually precisely as defined in the WalletConnect docs.
It isn't meant to send a message right now. Which is more than a little weird...

If you'd like to change the spec, I would recommend creating a PR or an issue request on the spec.

For here though, I am going to close this. I have resolved the issue of passing in a number that is too large =)
