### ISSUE TITLE
[Feature Request] support for silent timeout

### ISSUE THREAD

**Issue by dmdeklerk** [WalletConnect/WalletConnectFlutterV2#48]
In the current architecture there is no easy way to cause a "silent timeout" to invalid requests.
Instead if one looks at this code the `SignEngine._onSessionRequest` either sends a success response or a failure.

https://github.com/WalletConnect/WalletConnectFlutterV2/blob/ea8810eb0e5a26c48567cddb58215dbc3ab8a7d1/lib/apis/sign_api/sign_engine.dart#L1072-L1101

If we however look at the caip-25 standard there is recommendation to not respond to a caller at all in certain cases.

https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-25.md#privacy-considerations

The main idea is 

> To minimize this risk, and to minimize the data (including behavioral data) leaked by responses to potentially malicious CAIP-25 calls, respondents are recommended to ignore calls

Can we discuss a mechanism for this library to assist provider developers in ignoring these calls?

My suggestion would be to throw a `WalletConnectSilentTimeout` or something of that nature and in that case the request is removed from any pending requests and simply not sends a response.

**Comment by Luzzotica** [comment]
I am slowly realizing that while the function handler method for receiving requests seemed good in theory for simpler use cases, in practice it appears to not provide the flexibility necessary for more complex cases such as this one.

If you used the event approach you could simply filter the received requests and not respond to them as you see fit, which would be a solution to the above problem. 

All of the above being said, I am debating returning to having the event-driven approach be the recommended one. 

Any thoughts? It does put more work on you, the developers, who are using the library to create the event router, but it does provide increased flexibility in the long term.

**Comment by dmdeklerk** [comment]
>  in practice it appears to not provide the flexibility necessary for more complex cases such as this one.

I disagree. The registered handlers work great.
All thats lacking is a way to control that you don't send an error or a response.

The `WalletConnectSilentTimeout` would be an improvement over the other implementations as it now clearly communicates to the developer an important best practice as described in CAIP-25.

Usage of the handlers is quite straight forward

1. what your handler returns is returned to the dapp
2. any error you throw in your handler is sent to the dapp
3. if you throw WalletConnectSilentTimeout no reponse is sent

You could write a part of the documentation as to when to throw WalletConnectSilentTimeout, reasons can be:

1. dapp references address you did not authorize for some method
2. ... other things ...

This would make the developer aware that they have to check for this situation, something they would otherwise not be aware of?

**Comment by Luzzotica** [comment]
I will be adding this within the next 24 hours.

Been working on the example wallet, and I'm almost to the point where I need it. Sorry it's taken so long.
