### ISSUE TITLE
Missing headers, HTTPException. Affects version 1.2.1

### ISSUE THREAD

**Issue by dmdeklerk** [WalletConnect/WalletConnectFlutterV2#54]
On master currently this code fails every time on Ios and Android.
The relay server complains about missing Connection header and possibly other headers as well.
This causes an HttpException to be thrown and leaves the library unusable.

https://github.com/WalletConnect/WalletConnectFlutterV2/blob/master/lib/apis/core/relay_client/websocket/websocket_handler.dart#L54-L58

Affected versions
- master ❌
- version 1.2.1 on https://pub.dev/ ❌
- version 1.2.0 on https://pub.dev/ ✅

**Comment by Luzzotica** [comment]
This is resolved with version [1.2.2](https://pub.dev/packages/walletconnect_flutter_v2), a quick patch I pushed out when I noticed it wasn't working on iOS and Android.

I guess I didn't merge my changes into master when I pushed them out as a patch, I will do that now.
