### ISSUE TITLE
Will there be a Dart version of the WalletConnect Chat client?

### ISSUE THREAD

**Issue by hayderux** [WalletConnect/WalletConnectFlutterV2#57]
I'm currently using the WalletConnect Chat client in my TypeScript-based project, but I'm interested in porting it to Dart so that I can use it in a Dart-based project as well. I was wondering if there are any plans to create a Dart version of the WalletConnect Chat client, or if anyone has already attempted this.

**Comment by Luzzotica** [comment]
Nothing in the plans yet. The next piece to build for Flutter is the Web3Modal.
Once that's in place, we will take a look at further APIs being built out.
I don't have a timeline on when any of that will happen.

Obviously, if you'd like to build it yourself, feel free to do so! The dart lib as it stands is heavily inspired by the typescript implementation. You could likely continue that and build out the Chat client using the typescript implementation and the spec.
