### ISSUE TITLE
[Feature request] Add mobile linking support

### ISSUE THREAD

**Issue by 3ph** [WalletConnect/WalletConnectFlutterV2#60]
Firstly, great job creating the package!

Currently, the package only supports linking through a QR code. Do you plan to add support for mobile linking through universal/deep links?

I'm a creator of the [walletconnect_qrcode_modal_dart ](https://pub.dev/packages/walletconnect_qrcode_modal_dart) package for WalletConnect V1 mobile linking and so I'd like to see some support for V2 - either adding it to your package or add support to my package (or create a new one).

Please let me know your thoughts. Thanks!

**Comment by bobwith2bees** [comment]
@3ph Feel free to leverage this example app I am writing for a Flutter Web3 class.  It adds a few elements from the web3modal which your plugin doesn't have  https://web3modal.com    That said - I suspect you have a better understanding of the deep linking challenges.  ;-)

https://gitlab.com/graflr/flutter_web3_demo

Note the above it is not an official plugin or example. There is no implied sustaining or support on the code. That said, I will keep it running while I am teaching the class.

**Comment by Luzzotica** [comment]
When I begin work on the Web3Modal, I will work on this.
I'm putting together a plan of attack for the Web3Modal today.

**Comment by 3ph** [comment]
Great. Please let me know if you need any help with that. Cheers.

**Comment by DjToMeK30** [comment]
@Luzzotica thank you for working on this. Just a question. 
Do you maybe have any ETA on this?

**Comment by DjToMeK30** [comment]
Oh ok.. so it is still in the air
Do you have any recomendation on what to do if you were me? :)
So I would like to implement this flutter web3modal into my app, but current options are not the best without me coding what I guess will come from you/walletconnect team some day.
Should I just wait on this or start coding web3modal on my own?

**Comment by bobwith2bees** [comment]
@DjToMeK30  - As mentioned in the above comments, I wrote a simple modal you can use in the interim.  If you do write your own - you can have a working reference.   

I'm still working on the class, so I will keep updating the code for a couple of months.  (And I have to port it into my production app before the WalletV2 deadline.  ;-))

**Comment by DjToMeK30** [comment]
@bobwith2bees thank you for your code yes. The thing is that I need something for long term and something I will use in production code and I know walletconnect side is working on implemneting flutter/kotlin web3modal, and I don't want to reinvent the wheel if library will be able to do it soon. And ofc they will also update this in the future if something new comes up so I don't know if writing my own our using yours as a referece is smart at this point

**Comment by DjToMeK30** [comment]
@Luzzotica hello
I see now that official documentation is recomending this package for implementation in Flutter

So I see this feature is not yet supported but in a way needs to be for Android/iOS flutter. Is there any news regarding this feature or how should I handle this v2 situtation for mobile dev?

**Comment by Luzzotica** [comment]
I am working on this feature in this library:

https://github.com/Luzzotica/Web3ModalFlutter

**Comment by DjToMeK30** [comment]
Ok great! Thank you! <3
