### ISSUE TITLE
sending transaction no trx hash

### ISSUE THREAD

**Issue by AmjadKhan2k18** [WalletConnect/WalletConnectFlutterV2#61]
Hey I migrated from V1 to V2, in V1 when sending a transaction we get trxHash in response but in V2 it's not like that, can you update documentation with example how to extract trxHash from signResponse? 
```
final dynamic signResponse = await wcClient.request(
  topic: session.topic,
  chainId: 'eip155:1',
  request: SessionRequestParams(
    method: 'eth_sendTransaction',
    params: params,
  ),
);
```

**Comment by Luzzotica** [comment]
The objects returned by different chains is decided by the chain itself.

Perhaps look in to the ethereum [WalletConnectV2 docs](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) to see what you expect back from an `eth_sendTransaction` request.

If it's not returning what's expected, reach out the wallet themselves to ensure they have implemented the function correctly on their end.

**Comment by AmjadKhan2k18** [comment]
@Luzzotica  I am not getting response from any chain

I have connected TrustWallet 

and tried 4 chains

["1", "137", "56", "43114"]

my transaction is sent successfully but I am not getting any response at all

here is my code

``` 
final response = await _trustWcV2
              .request(
                topic: sessionData.topic,
                chainId: 'eip155:$chainId',
                request: SessionRequestParams(
                  method: 'eth_sendTransaction',
                  params: [trxParams],
                ),
              )
```

**Comment by AmjadKhan2k18** [comment]
Today I checked and there was update for TrustWallet on IOS after updating it, I am getting trx Hash now Thanks
