### ISSUE TITLE
Cannot add event after closing

### ISSUE THREAD

**Issue by r-oman-G** [WalletConnect/WalletConnectFlutterV2#64]
Hi, i founded a problem with after 10-15 minutes i see a event "Cannot add event after closing" and i reconnect doesn't work 

is it possible to work around that? 

The problem affect on any Interaction with dapp wallet connect, after 10-15 minutes i can't do nothing with dapp(cant receive requests, events, create new pairing or decline proposal) 

I'm using walletconnect_flutter_v2: ^1.2.3
Platform: mobile, we are using it for our crypto wallet project

**Comment by bobwith2bees** [comment]
Do you have any logic to restore the relay connection on a disconnect event?

For example: https://gitlab.com/graflr/flutter_web3_demo/-/blob/main/lib/services/walletconnect_service.dart#L427 

There was some work done with issue #34   but I still find I have to listen for the event and reconnect.  I'll let the project owner comment officially ;-)

**Comment by r-oman-G** [comment]
@bobwith2bees hi, thanks for answer 

I'm using the code 
 ```
   ///reconnect after disconnect
    signClient.core.relayClient.onRelayClientDisconnect.subscribe((args) {
      signClient.core.relayClient.connect(relayUrl: signClient.core.relayUrl);
    });
```

but connect again doesn't work and always throw `error: Bad state: The client is closed.`

**Comment by Luzzotica** [comment]
I'll look into this. I believe I had fixed it with my auto-reconnect functionality, but that's obviously not the case. 
Even the fact that you can't reconnect is strange. 
Thanks for bringing it! Sorry for the late reply!
