### ISSUE TITLE
What's the correct flow to pair a dApp and wallet for the first time?

### ISSUE THREAD

**Issue by mik3mast3rs** [WalletConnect/WalletConnectFlutterV2#66]
Hello!

For me, there is a lot of confusion about what's the correct way to pair a dApp and a wallet for the first time. Now, after re-reading again the documentation, I think it should go something like:

1. Init the wcClient in dApp and wallet
2. Get the pairing URI fron the dApp.
3. Call wcClient.pair(uri: URI) in the wallet without any confirmation dialog
4. Wait for the onSessionProposal listener to trigger and only then show the confirmation dialog. Only in this way we also can access the metadata of the dApp from the wallet

Is this right? I find it a bit counter-intuitive that you have to pair first in order to access the dApp metadata.

Can the dApp send requests or events to the wallet if it's just paired and doesn't have an active session?

Should you unpair if the user rejects the session in onSessionProposal?

And how do you reconnect to the dApp a second time, with one pairing being active? Currently, I am checking if there is an active pairing and, if so, I call wcClient.connect with that pairingTopic. What if you have an active session? Can you call wcClient.connect witth the sessionProperties?

**Comment by Luzzotica** [comment]
Your flow is correct!

If you have an active session, just use the active session, unless it doesn't have the information you need (Like if you need another wallet connected to sign a multisig account).

You don't need to reconnect or repair if the session is still active and you can retrieve it.

> Should you unpair if the user rejects the session in onSessionProposal?

Good question. I would say yes, as the pairing alone is rather useless, but this is up to you. If you don't delete it, you could reuse it, but that might be confusing to some users. Deleting it, and showing the QR code again is your best bet.

If you don't delete it, and end up reusing it, you won't have to have the user scan the QR code again, as steps 1-3 are meant to setup a pairing.

I hope I'm being clear enough to be understood. 
Let me know if you have more questions.
The [documentation](https://docs.walletconnect.com/2.0/advanced/what-changed-from-v1.0) is also rather good!
