### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by LvDj** [WalletConnect/WalletConnectFlutterV2#67]
https://github.com/WalletConnect/WalletConnectFlutterV2/issues
It's similar to this problem

String qrStr = "wc:709e8be6-8e56-4d09-a6e3-43c7e62e149a@1?bridge=https%3A%2F%2Fc.bridge.walletconnect.org&key=7c55a917d7d8f39077d01b1d172c7e653fc7fb50c4842cb854fac439e20bec2c";
Uri uri = Uri.parse(qrStr);
PairingInfo info = await wcClient.pair(uri: uri);

but:
URIParseResult ret = URIParseResult(
      protocol: protocol,
      version: splitParams[1],
      topic: splitParams[0],
      symKey: uri.queryParameters['symKey']!,   <<<<<-------- this error
      relay: Relay(
        uri.queryParameters['relay-protocol']!,
        data: uri.queryParameters.containsKey('relay-data')
            ? uri.queryParameters['relay-data']
            : null,
      ),
      methods: methods,
    );

**Comment by minemos** [comment]
check uri is correct.
uri is different from v1

**Comment by LvDj** [comment]
> check uri is correct.
> uri is different from v1

My SDK uses V1. ?
Again, the url is v1 ?

**Comment by LvDj** [comment]
thank you
 
I found the problem because the etherscan.io website uses v1
 
can look https://github.com/WalletConnect/web-examples
use web-examples demo, Generate QR code
