### ISSUE TITLE
trust wallet can connect to demo，but can not author to demo

### ISSUE THREAD

**Issue by taichushouwang** [WalletConnect/WalletConnectFlutterV2#72]
Hi, I want to make my new dApp, but when I try to connect Trust Wallet with dapp demo. Trust Wallet can connect to dapp, there is also a session with Trust Wallet in dapp, but when I check the log and the code. 
```
debugPrint('Awaiting authentication response');
final authResponse = await authRes.completer.future;
```
It will stuck in this code in the **connect_page.dart**. In the session it only can use method personal_sign and eth_sign, and the other method can not use.

and I also change the params of requestAuth like this:
```
      final param = AuthRequestParams(
        chainId: chainId,
        domain: sessionData.peer.metadata.url.replaceAll('https://', ''),
        aud: '${sessionData.peer.metadata.url}/login',
      );
      final AuthRequestResponse authRes = await widget.web3App.requestAuth(
        pairingTopic: pairingTopic,
        params: param,
      );
```
Did I do something wrong? Thx

**Comment by Luzzotica** [comment]
I tested the auth on Thursday and it wasn't hanging.
It was however failing to authenticate. Whatever I was getting back from Trust Wallet couldn't be verified with the public key.

What version of Trust Wallet do you have?

**Comment by Luzzotica** [comment]
I've tested my demo applications with trust wallet and it works, I am closing this issue.

**Comment by taichushouwang** [comment]
I'm sorry for the slow reply. I use version of Trust Wallet is 7.18.1.
If you tested demo successfully, can you show your code for `AuthRequestParams` and `requestAuth`

**Comment by taichushouwang** [comment]
after I update the version of Trust Wallet from 7.18.1 to 7.19.2, and update the demo code for the lastest version, this issue solved. Thx.
