### ISSUE TITLE
Saving sessions with walletconnect v2 flutter package 

### ISSUE THREAD

**Issue by Bravark** [WalletConnect/WalletConnectFlutterV2#75]
Hello i have been having issues with getting the session that currently active when a user connects their wallet. I'm using the Flutter SDK.

The Sdk has the function of getActiveSession which returns nothing when I call it.

I posted this on the discord channel but it seems this is the place where I can get responses.

**Comment by Bravark** [comment]
To follow up on this conversation, this is our code.

Future<void> checkSavedWallets() async {
    await Future.delayed(const Duration(seconds: 2));
    final sessions = AppSignClient.instance.signClient.getActiveSessions();
    print('SESSIONS $sessions');
    if (sessions.isNotEmpty) {
      for (var i in sessions.entries) {
        if (i.value.requiredNamespaces!.values.first.chains!
            .contains(EthereumConnector.chain)) {
          state.connectors.add(
            EthereumConnector.walletConnectorFromSessionData(i.value),
          );
        } else if (i.value.requiredNamespaces!.values.first.chains!
            .contains(BinanceConnector.chain)) {
          state.connectors.add(
            BinanceConnector.walletConnectorFromSessionData(i.value),
          );
        }
      }
      state = state.copyWith();
    }
  }
This function is called everytime the app is opened and even if we have connected to a session before it was closed, getActiveSession still returns an empty map.

class AppSignClient {
  AppSignClient._private();

  static final AppSignClient _instance = AppSignClient._private();

  static AppSignClient get instance => _instance;

  late Web3App signClient;

  Future<void> initClient() async {
    signClient = await Web3App.createInstance(
      relayUrl: 'wss://relay.walletconnect.com',
      projectId: '<OUR_PROJECT_ID>',
      metadata: const PairingMetadata(
        name: 'Pouch',
        description: 'A dapp that can request that transactions be signed',
        url: 'https://walletconnect.com',
        icons: ['https://avatars.githubusercontent.com/u/37784886'],
      ),
      memoryStore: true,
    );
  }
}

This is the content of AppSignClient.
static const String chain = 'eip155:1';

  @override
  Web3App get signClient => AppSignClient.instance.signClient;

  @override
  Future<bool> initWallet() async {
    ConnectResponse response = await signClient.connect(
      requiredNamespaces: {
        'eip155': const RequiredNamespace(
          chains: [chain],
          methods: [
            'eth_signTransaction',
            'eth_sendTransaction'
          ],
          events: [],
        ),
      },
    );

    Uri? uri = response.uri;
    launchUrl(uri!);

    try {
      session = await response.session.future;
    } catch (e) {
      rethrow;
    }

    return session.acknowledged;
  }

**Comment by Luzzotica** [comment]
```dart
memoryStore: true,
```

Remove this line from the initialization to make the sessions be persisted to local storage when they update.
`memoryStore` set to true basically tells the library "Save nothing, delete it all when my app closes"

If removing that line doesn't resolve the issue, let me know, otherwise, please close this issue.

**Comment by Bravark** [comment]
Thanks that solved the issue
