### ISSUE TITLE
Robustness - SecretBox has wrong message authentication code (MAC)

### ISSUE THREAD

**Issue by bobwith2bees** [WalletConnect/WalletConnectFlutterV2#77]
BitKeep Android 7.3.4 appears to have a bad implementation for Ping Pairing.  Session Pairing in their UI works.   Just logging for better error handling on the package side.   Not a high priority for me.

Steps to reproduce:

1. Connect to BitKeep
2. Perform a Pairing Ping from our client (DAPP).
- Ping appears to send find from DAPP
- BitKeep response is possibly malformed, and the WalletConnectV2 package gets an Unhandled Exception

Expectation:
- Malformed packets/messages are dropped  and event reported via onRelayClientError

pairing.dart - need to catch the error from core.crypto.decode
``` dart 
    // Decode the message
    String? payloadString = await core.crypto.decode(
      event.topic,
      event.message,
      options: DecodeOptions(
        receiverPublicKey: receiverPublicKey?.publicKey,
      ),
    );
```

```
I/flutter ( 7523): 19:45:52 🐛 HomePage        - Ping Pairing BitKeep
I/flutter ( 7523): 19:45:52 🐛 WalletConnctSvc - pingPairing - topic: 031a9eb332dfdb563c081c05bed258dd1d55cbd104514a0cd3909bba8ec7c3d7
I/flutter ( 7523): 19:45:57 🐛 HomePage        - AppLifecycleState: AppLifecycleState.inactive.
I/flutter ( 7523): 19:45:58 🐛 HomePage        - AppLifecycleState: AppLifecycleState.paused.
I/flutter (28973): _handleMethod:
I/flutter (28973): _handleMethod:
I/flutter (28973): _handleMethod:
E/flutter ( 7523): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SecretBoxAuthenticationError: SecretBox has wrong message authentication code (MAC)
E/flutter ( 7523): #0      DartCipherState.convert (package:cryptography/src/dart/dart_cipher.dart:163:7)
E/flutter ( 7523): <asynchronous suspension>
E/flutter ( 7523): #1      DartCipherWithStateMixin.decrypt (package:cryptography/src/dart/dart_cipher.dart:421:23)
E/flutter ( 7523): <asynchronous suspension>
E/flutter ( 7523): #2      CryptoUtils.decrypt (package:walletconnect_flutter_v2/apis/core/crypto/crypto_utils.dart:145:22)
E/flutter ( 7523): <asynchronous suspension>
E/flutter ( 7523): #3      Crypto.decode (package:walletconnect_flutter_v2/apis/core/crypto/crypto.dart:182:28)
E/flutter ( 7523): <asynchronous suspension>
E/flutter ( 7523): #4      Pairing._onMessageEvent (package:walletconnect_flutter_v2/apis/core/pairing/pairing.dart:604:29)
E/flutter ( 7523): <asynchronous suspension>

```

**Comment by Luzzotica** [comment]
I would actually expect this to throw an error at the pairing level, not the relay client error.

The pairing is the one with the information on the MAC and how to encode/decode messages, the relay client just forwards the information. Thus the pairing is aware of the error, and not necessarily the relay client.

Perhaps a new event should be created when the pairing fails to decode a message, as shown above.

Does that sound reasonable? Maybe not, it might just be another event to listen in on...

This could also be an issue with my encoder/decoder, however if it only exists for a pairing ping, I doubt that is the case.

**Comment by bobwith2bees** [comment]
Flexible on where / how to report.   If it's a malformed message, the less processing the better.  But it is still important to be able to account for all the bytes sent/received  with the relay.   So if it was a valid relay packet, but invalid as a Pairing Ping your logic makes sense to throw an error at the pairing level.

I'll update this issue if I see it from other wallets.  I suspect it's just a bug on the wallet side as we all get out V2 versions out.  

I am still working on the best way to handle both kinds of pings(Pairing and Session) and keep counters for success/timeouts/other errors.  I can open a separate issue to clarify those questions after I have done more homework.

**Comment by Luzzotica** [comment]
I remember seeing this, but have not seen it in some time.
I didn't intentionally fix it, but I have been working with different auth things. I may have inadvertently resolved it. 

If you haven't seen it since the 2.0.6 update, would you mark this as closed for me please?

**Comment by bobwith2bees** [comment]
Tested wit 2.0.7 against Bitkeep 7.3.5 and no longer see any errors thrown from the WalletConnect package.  Closing.

**Comment by bobwith2bees** [comment]
Tested with 2.0.8 today and I see the error.    I was testing incorrectly before (Session ping from wallet) so disregard my closing comments.

What I wanted to use pairng ping to do 
* Verify my DAPP communication to the WalletConnect Relays is up.  

What I did:
 *  core.pairing.ping(topic: pairingTopic);
 * The paring topic was taken from the pairingInfo.topic returned from core.pairing.getPairings();

The testing wallets showed an incorrect/expired URI error.   The error returned via the protocol triggers the SecretBox error on my DAPP.  

Question:
* Could the error returned be in plaintext?
* Did I use the incorrect topic?

**Comment by bobwith2bees** [comment]
Attempted to test with WalletConnect package 2.1.4.

The Bitkeep wallet is no longer listed on the Wallet Connect Cloud Registry
https://walletconnect.com/explorer?search=bitkeep

Closing this issue as no longer testable. (reproducible)

**Comment by Luzzotica** [comment]
They were "using an ancient version of the WalletConnect repo" 

They also rebranded to BitGet I think.

Thanks for cleaning up the issue @bobwith2bees !
