### ISSUE TITLE
How to get the wallet balance like react version in the flutter version

### ISSUE THREAD

**Issue by taichushouwang** [WalletConnect/WalletConnectFlutterV2#78]
Hi, in the [https://react-auth-dapp.walletconnect.com/](https://react-auth-dapp.walletconnect.com/) demo, after we scan QR code, we can sign in the wallet, and can see the balance for the ETH, but in the flutter demo, we can not get the balance, I can not find any data about balance in the log. So how can I get the balance in ther flutter version?

**Comment by Luzzotica** [comment]
This is part of the Web3Modal that I will begin building this week in a new repo. 

It is not part of the base SignAPI that exists in this repo.

I'll post here later with the new repo so you can follow the progress on this feature.

**Comment by bobwith2bees** [comment]
@taichushouwang  - For EVM compatible chains you can use the web3dart package with a node API provider.  
 
 From: https://pub.dev/packages/web3dart#connecting-to-an-rpc-server
 ```dart
 // You can now call rpc methods. This one will query the amount of Ether you own
EtherAmount balance = ethClient.getBalance(address);
print(balance.getValueInUnit(EtherUnit.ether));
```

**Comment by taichushouwang** [comment]
> @taichushouwang - For EVM compatible chains you can use the web3dart package with a node API provider.
> 
> From: https://pub.dev/packages/web3dart#connecting-to-an-rpc-server
> 
> ```dart
> // You can now call rpc methods. This one will query the amount of Ether you own
> EtherAmount balance = ethClient.getBalance(address);
> print(balance.getValueInUnit(EtherUnit.ether));
> ```

Thx, I will check this

**Comment by Luzzotica** [comment]
I will be adding this functionality to this new repo:

https://github.com/Luzzotica/Web3ModalFlutter
