### ISSUE TITLE
Incorrect methods name for approving and rejecting a session?

### ISSUE THREAD

**Issue by mik3mast3rs** [WalletConnect/WalletConnectFlutterV2#8]
The documentation mentions two methods for approving and rejecting a session proposal:

`await wcClient.approve(
  id: id,
  namespaces: walletNamespaces // This will have the accounts requested in params
);`

`await wcClient.reject(
  id: id,
  reason: ErrorResponse(
    code: 4001,
    message: "User rejected request",
  ),
);`

But the wcClient, being a Web3Wallet object, doesn't have those methods. Are you referring to **approveSession** and **rejectSession**? Their signatures are similar with the ones mentioned in the documentation.

**Comment by Luzzotica** [comment]
Yep! Let me fix that.

Thank you!
