### ISSUE TITLE
No matching key. session topic doesn't exist

### ISSUE THREAD

**Issue by YannMarti** [WalletConnect/WalletConnectFlutterV2#80]
After connecting a dApp to a wallet pinging fails and calling any rtegistered method throws "No matching key. session topic doesn't exist" in the dapp. Im used https://react-app.walletconnect.com/ to test this.

Steps to reproduce: 
-Start example wallet of this package
- connect wallet with https://react-app.walletconnect.com/
- try any method

This was still working last tuesday (09.05.2023)

might be related to this: https://github.com/WalletConnect/walletconnect-monorepo/issues/2379

Im still posting the issue as  im not sure if its a problem from this package, as https://react-wallet.walletconnect.com/walletconnect works with https://react-app.walletconnect.com/

**Comment by YannMarti** [comment]
I did some more testing and it seems that sessions dont get added properly for some reason. From my understanding after web3Wallet.approveSession is called, the session should be added to the web3Wallet. but when i call web3Wallet!.sessions.getAll() i get an empty list, despite just having approved the session. Does the issue lie here, or am i misunderstanding something?

**Comment by Luzzotica** [comment]
Looking into it now.

**Comment by mik3mast3rs** [comment]
> I did some more testing and it seems that sessions dont get added properly for some reason. From my understanding after web3Wallet.approveSession is called, the session should be added to the web3Wallet. but when i call web3Wallet!.sessions.getAll() i get an empty list, despite just having approved the session. Does the issue lie here, or am i misunderstanding something?

Your issue is similar to mine: https://github.com/WalletConnect/WalletConnectFlutterV2/issues/79 After I approve a session in the wallet, I can find it in the dApp, but not in the wallet.

**Comment by Luzzotica** [comment]
I can confirm that tests I had in my repo that worked 5 days ago are now functioning strangely. 

Some update must have been pushed through on the relay server. I'm trying to resolve it now.
