### ISSUE TITLE
Update dependencies and Dart version

### ISSUE THREAD

**Issue by tim-eucalyptus** [WalletConnect/WalletConnectFlutterV2#82]
Dart 3.0.0 is now available. 

Also many dependency updates are available:
<img width="380" alt="Screenshot 2023-05-17 at 4 16 27 PM" src="https://github.com/WalletConnect/WalletConnectFlutterV2/assets/104312722/3d9ee022-9191-4afb-b5cc-2becbe9f5932">

**Comment by Luzzotica** [comment]
Resolved with v2.0.7
