### ISSUE TITLE
[Request] Clarification on Pings 

### ISSUE THREAD

**Issue by bobwith2bees** [WalletConnect/WalletConnectFlutterV2#85]
Working with pings.  This is what I believe is correct - looking to be corrected :-)

# Pairing vs Session Ping
* The pairing ping validates the core relay can talk to the peer.  
* The session ping corresponds to the negotiated Sign client session and is the preferred ping method. 

# Responding to Pings
- The WalletConnectFlutterV2 package will validate and automatically respond to pings initiated from connected peers.
- You can listen to those events via _core.pairing.onPairingPing.subscribe_ and _signEngine.onSessionPing.subscribe_. 
- There is no response detail provided (response sent inticated success or failure due to invalid/expired session?)
```
signEngine.onSessionPing - received on topic: 3ec9ec6495c95b5471643dfec090cfa4fe7cb36f5d40ffc58feb3c673b92127d id: 1684416983385397   
```
 
# Sending Pings
- To initiate a ping use _core.pairing.ping(topic: pairingTopic)_ and _signClient.ping(topic: sessionData.topic)_.
- To determine success, timeout, or failure.... **this is where I get lost**  Does the app manage this?

I thought you could listen for a relay message with the topic echo'ed back from the peer.  From
https://docs.walletconnect.com/2.0/android/sign/wallet-usage#session-ping

> To ping a peer with a session, call SignClient.ping with the Sign.Params.Ping with a session's topic. If ping is successful, topic is echo'd in listener.

Would I see that by listening to: core.relayClient.onRelayClientMessage and then decoding the message to verify the topic is there?   I am not seeing any, but I used to see a relay message reported.  Now I am ready to decode it... I don't see it. :-/

# Interop notes:
* Bitkeep 7.3.4 for IOS - Wallet can send and receive session pings, reporting success.
* Bitkeep 7.3.5 for Android - Wallet can send session pings but reports failure.  
* looking for more wallets to test (with ping features)
 
 # Steps to reproduce
 * You can use my test app https://gitlab.com/graflr/flutter_web3_demo
 * Once a wallet is connected, the session ping and pairing ping tests are slide-able actions
 
![image](https://github.com/WalletConnect/WalletConnectFlutterV2/assets/81196211/5d39dd2c-f738-4d58-9aa3-92aca6c44daa)

**Comment by Luzzotica** [comment]
The lib _should_ handle the failure responses and timeouts.
I'm not saying that it does. There isn't a whole lot of common documentation on how it works. I have copied the functionality of the JS monorepo.

Perhaps we could bring some more clarity to the overarching docs on this.

At the end of the day though, you shouldn't strictly need to ping sessions or pairings, as the libraries should manage keeping the connection alive for you.

**Comment by Luzzotica** [comment]
Definitely don't use ping delay to determine which wallet is closer. That will not work as you hope I suspect.

Yep and yep to everything else! Closing!
