### ISSUE TITLE
Example dapp can't complete authentication - Android Metamask v6.5.0

### ISSUE THREAD

**Issue by PramodJoshi** [WalletConnect/WalletConnectFlutterV2#86]
I'm testing example dapp. It pairs fine with Metamask but can't complete authentication. It's stuck at 'Await authentication response'. I'm not getting authentication request in Metamask either.

Chain: Polygon Mainnet
Console log:
```
flutter: Awaiting session proposal settlement
flutter: Requesting authentication
flutter: Awaiting authentication response
```

**Comment by bobwith2bees** [comment]
My Metamask notes / cross references:

* WalletConnect V1  - Has an open issue https://github.com/MetaMask/metamask-mobile/issues/6387
* WalletConnect V2  - Wait for the Wallet Connect v2 branch to merge: https://github.com/MetaMask/metamask-mobile/tree/feat/walletconnect-v2  (i.e. There is no WalletConnect V2 support yet.)

**Comment by PramodJoshi** [comment]
@bobwith2bees Ah, that's it.

Thank you both for the quick response.
