### ISSUE TITLE
personal_sign validation fails with hex-string in example wallet

### ISSUE THREAD

**Issue by YannMarti** [WalletConnect/WalletConnectFlutterV2#89]
Im using https://react-app.walletconnect.com/ to test my wallet function. The dApp sends a hex-string as a message on personal_sign. If signed with the provided example wallet the dApp fails to verify the signature.
This is because the example wallet uses Uint8List.fromList((message as String).codeUnits) but the dApp something akin to hex.decode. Per definition in eip-191 the message can be any arbitrary data, does that mean the verification in the dApp is done incorrectly or should there be a seperate case added to the wallet if the message is a hex-string?

**Comment by Luzzotica** [comment]
Have you pulled the most recent code?

This should have been resolved this last week, and the code for personalSign on the wallet side is now this:

```
Future personalSign(String topic, dynamic parameters) async {
    print('received personal sign request: $parameters');

    final String message = EthUtils.getUtf8Message(parameters[0]);

    final String? authAcquired = await requestAuthorization(message);
    if (authAcquired != null) {
      return authAcquired;
    }

    try {
      // Load the private key
      final List<ChainKey> keys = GetIt.I<IKeyService>().getKeysForChain(
        getChainId(),
      );
      final Credentials credentials = EthPrivateKey.fromHex(keys[0].privateKey);

      final String signature = hex.encode(
        credentials.signPersonalMessageToUint8List(
          Uint8List.fromList(
            utf8.encode(message),
          ),
        ),
      );

      return '0x$signature';
    } catch (e) {
      print(e);
      return 'Failed';
    }
  }
```

After reading through `ethers` code, the JS implementation to help people sign transactions and the like, they have a method of transforming hex data into utf8 data that I have copied in my wallet.
However, this is not required: If the data received is not hex data it will be handled as is, with no transformation or alteration.

I have no idea where or if that hex to utf8 is documented anywhere, I was definitely in a "monkey-see, monkey-do" state when I did it.

If updating to the newest version of library resolves the problem, then please close this issue. Thanks!

**Comment by YannMarti** [comment]
yes, didnt pull the newest version, works in that one
