### ISSUE TITLE
how can I connect bitcoin network

### ISSUE THREAD

**Issue by taichushouwang** [WalletConnect/WalletConnectFlutterV2#95]
Hi, I see in the chain_data.dart, there are many chain, such as Ethereum, Solana and Kadena. But I don't see the Bitcoin. So does walletconnect support Bitcoin? If it supports, how can we connect Bitcoin?

**Comment by taichushouwang** [comment]
Thx for replay, I'm new to web3. And my purpose is just connect to bitcoin wallet(I'm building a dapp), And I want to know that how to find the bitcoin network's ChainId and the ChainType

**Comment by bobwith2bees** [comment]
@taichushouwang  From the spec: https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-2.md

```
# Bitcoin mainnet (see https://github.com/bitcoin/bips/blob/master/bip-0122.mediawiki#definition-of-chain-id)
bip122:000000000019d6689c085ae165831e93
```

You would still need to know the methods to request in order to pair sign etc.  

Until there is a wallet published (see https://walletconnect.com/explorer) you might be stuck.

**Comment by taichushouwang** [comment]
Thanks for reply, I will close this issue
