### ISSUE TITLE
Connect Modal not opening in Metamask (iOS)

### ISSUE THREAD

**Issue by kinggongzilla** [WalletConnect/WalletConnectFlutterV2#98]
When running the example application and scanning the QR Code with an iPhone 13, I am redirected to Metamask. However Metamask does not show a "Connect" modal, where the user can connect his wallet.

It does work for Trust Wallet. I have not tried other wallet applications.

Metamask Version: 6.3.0

**Comment by Luzzotica** [comment]
Are you saying you scanned it with your camera normally and it redirected you to Metamask, or are you trying to scan from Metamask itself?

Please be a bit more specific in your description.

**Comment by kinggongzilla** [comment]
@Luzzotica 
Thanks for your quick reply!

I scanned it with the iPhone camera, which redirected me to MetaMask. No Popup appeared in Metamask.
However when I only have Trust Wallet installed, Trust Wallet is opened by scanning the QR Code with the iPhone camera. A popup to connect appears in Trust Wallet.

I hope this describes my issue clearly enough. Please let me know if I can provide more details

**Comment by Luzzotica** [comment]
Ok, this is a problem with metamask, not flutter.

Please post the issue in their github: https://github.com/MetaMask/metamask-mobile
